### PR TITLE
Fix rgb

### LINKED ISSUE #5551: [bmon] Failed to build
```
checking for NcursesW wide-character library... yes
checking for working ncursesw/curses.h... no
checking for working ncursesw.h... no
checking for working ncurses.h... no
configure: WARNING: could not find a working ncursesw/curses.h, ncursesw.h or ncurses.h
configure: error: requires an X/Open-compatible Curses library with color
bmon failed to build: `./configure --prefix=/usr/local --libdir=/usr/local/lib --mandir=/usr/local/share/man --build=armv7l-cros-linux-gnueabihf --host=armv7l-cros-linux-gnueabihf --target=armv7l-cros-linux-gnueabihf --program-prefix='' --program-suffix=''             --without-ncurses             --with-ncursesw` exited with 1
```

### PR DESCRIPTION
**Pull request by saltedcoffii**
Helps fix #5551 (hopefully)

@satmandu this will need binaries

### CODE REVIEW

**Comment by satmandu** [comment]
Awesome. I should be able to get to generating binaries later today.

File: packages/rgb.rb [hunk 1]
```diff
@@ -2,35 +2,21 @@
 
 class Rgb < Package
   description 'X color name database'
-  homepage 'https://xorg.freedesktop.org'
+  homepage 'https://xorg.freedesktop.org/'
   version '1.0.6'
```
Comment (uberhacker) [inline packages/rgb.rb:6]: Bump version?

**Comment by satmandu** [comment]
binaries added

**Review by satmandu — APPROVED** [review]
