### PR TITLE
downloader.rb: add `file://` protocol support, fallback to `curl` when the protocol is not `http(s)://`/`file://`

### LINKED ISSUE #6518: Unable to install local binaries
A package with a local binary cannot be installed.

```
  binary_url({                                                                                                                                       
    x86_64: 'file://...'                                        
  })
```
```
/usr/local/lib64/ruby/3.0.0/net/http.rb:987:in `initialize': Failed to open TCP connection to :80 (Connection refused - connect(2) for "" port 80) (Errno::ECONNREFUSED)
        from /usr/local/lib64/ruby/3.0.0/net/http.rb:987:in `open'
        from /usr/local/lib64/ruby/3.0.0/net/http.rb:987:in `block in connect'
        from /usr/local/lib64/ruby/3.0.0/timeout.rb:97:in `block in timeout'
        from /usr/local/lib64/ruby/3.0.0/timeout.rb:107:in `timeout'
        from /usr/local/lib64/ruby/3.0.0/net/http.rb:985:in `connect'
        from /usr/local/lib64/ruby/3.0.0/net/http.rb:970:in `do_start'
        from /usr/local/lib64/ruby/3.0.0/net/http.rb:959:in `start'
        from /usr/local/lib64/ruby/3.0.0/net/http.rb:621:in `start'
        from /usr/local/lib/crew/lib/downloader.rb:24:in `downloader'
```

### PR DESCRIPTION
**Pull request by supechicken**
Fixes #6518 

Copy from filesystem if the protocol in the given URL is `file://`
If the protocol is not `http(s)://` nor `file://`, use `curl`

Tested on `x86_64`

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/supechicken666/chromebrew.git CREW_TESTING_BRANCH=downloader_file_protocol CREW_TESTING=1 crew update
```

### CODE REVIEW

File: lib/downloader.rb [hunk 1]
```diff
@@ -21,6 +21,28 @@ def downloader (url, filename = File.basename(url), retry_count = 0, verbose = f
...
   uri = URI(url)
 
+  case uri.scheme
+  when /http?/
+  when 'file'
+    # use FileUtils to copy if it is a local file (the url protocol is file://)
+    if File.exist?(uri.path)
+      return FileUtils.cp uri.path, filename
+    else
+      abort "#{uri.path}: File not exist :/".lightred
```
Comment (uberhacker) [inline lib/downloader.rb:31]: `File not found` is better?

File: lib/downloader.rb [hunk 2]
```diff
@@ -21,6 +21,28 @@ def downloader (url, filename = File.basename(url), retry_count = 0, verbose = f
   trap('WINCH') { setTermSize }
   uri = URI(url)
 
+  case uri.scheme
+  when /http?/
```
Comment (uberhacker) [inline lib/downloader.rb:25]: What do we do about `ftp` and other protocols?

**Comment by saltedcoffii** [comment]
can we use the net library to support ftp:// URLs?

File: lib/downloader.rb (hunk 2 above)
Comment (supechicken) [reply lib/downloader.rb:25]: Fallback to `curl`:

https://github.com/skycocker/chromebrew/pull/6520/files#diff-46c0af844c07a052d4a9dd139bf6e2d494a7032fed363960eaedaf4bc82c9e8dR33-R44

**Comment by supechicken** [comment]
> can we use the net library to support ftp:// URLs?

Yes, there is a library called [`net/ftp`](https://ruby-doc.org/stdlib-2.4.0/libdoc/net/ftp/rdoc/Net/FTP.html), maybe we can implement it in the next PR

File: lib/downloader.rb (hunk 1 above)
Comment (supechicken) [reply lib/downloader.rb]: Change made

File: lib/downloader.rb (hunk 2 above)
Comment (uberhacker) [reply lib/downloader.rb:25]: It would be more elegant to use net/http for ftp.  Possible?

File: lib/const.rb [hunk 3]
```diff
@@ -1,6 +1,6 @@
 # Defines common constants used in different parts of crew
 
-CREW_VERSION = '1.20.0'
+CREW_VERSION = '1.20.1'
```
Comment (uberhacker) [inline lib/const.rb:3]: Bump to `1.20.3`?

File: lib/downloader.rb (hunk 2 above)
Comment (satmandu) [reply lib/downloader.rb:25]: Is https://ruby-doc.org/stdlib-2.7.0/libdoc/open-uri/rdoc/OpenURI.html another option? Since it wraps HTTP and FTP?

File: lib/const.rb (hunk 3 above)
Comment (supechicken) [reply lib/const.rb]: Done

File: lib/downloader.rb (hunk 2 above)
Comment (supechicken) [reply lib/downloader.rb:25]: It is a much better solution :)
