### PR TITLE
Rust -> 1.55.0

### LINKED ISSUE #6190: [rust] Unable to build on i686
```
$ crew build rust
rust: Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.
Downloading source...
Building from source, this may take a while...
Rename all *.la files to *.la_tmp
Preconfiguring package...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21102  100 21102    0     0  40706      0 --:--:-- --:--:-- --:--:-- 93371
info: downloading installer
info: profile set to 'minimal'
info: setting default host triple to i686-unknown-linux-gnu
info: syncing channel updates for 'stable-i686-unknown-linux-gnu'
thread 'main' panicked at 'range start index 355 out of range for slice of length 32', /cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.2/src/util_libc.rs:65:24
stack backtrace:
   0: 0x77365023 - std::backtrace_rs::backtrace::libunwind::trace::h7fd0e141e2d906ca
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1: 0x77365023 - std::backtrace_rs::backtrace::trace_unsynchronized::h1eca8ded787c5b24
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: 0x77365023 - std::sys_common::backtrace::_print_fmt::h4cb0f8f7cda4d345
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3: 0x77365023 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2579a3d2b4303078
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4: 0x76f78164 - core::fmt::write::h02e8615e652766ba
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5: 0x773648de - std::io::Write::write_fmt::h92c644d2cf74e57f
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6: 0x77364300 - std::sys_common::backtrace::_print::h9b13230a85311925
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7: 0x77364300 - std::sys_common::backtrace::print::h5482833abe329a2b
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8: 0x77364300 - std::panicking::default_hook::{{closure}}::h68d5f6db0f5d7902
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9: 0x773638c6 - std::panicking::default_hook::h82ae8b9a767d7b31
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10: 0x76f15f08 - rustup::currentprocess::with::{{closure}}::{{closure}}::h30fa267c30e0f5f6
  11: 0x773634ca - std::panicking::rust_panic_with_hook::hc3227ec8c33f6507
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:595:17
  12: 0x77382bb2 - std::panicking::begin_panic_handler::{{closure}}::h0408582b591d5da8
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:497:13
  13: 0x77382b1a - std::sys_common::backtrace::__rust_end_short_backtrace::h8bfb2d3fce40ba2b
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  14: 0x77382aa1 - rust_begin_unwind
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  15: 0x76effcf5 - core::panicking::panic_fmt::h50032c7c716249f8
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
  16: 0x76f0016f - core::slice::index::slice_start_index_len_fail::hf81767729ae36c6a
                       at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/slice/index.rs:34:5
  17: 0x7707c7b8 - <rand_core::os::OsRng as rand_core::RngCore>::try_fill_bytes::hbe5b92d8708ff51f
  18: 0x7707c2b0 - std::thread::local::fast::Key<T>::try_initialize::h3f6f74dea40548cb
  19: 0x77290a67 - rustup::utils::raw::random_string::h201d9ea95dbc64f4
  20: 0x772902df - rustup::dist::temp::Cfg::new_file_with_ext::hc273008c953d79ae
  21: 0x7727f8c2 - rustup::dist::download::DownloadCfg::download_and_check::h9bc00d4eee4a5de3
  22: 0x7726c7e5 - rustup::dist::dist::dl_v2_manifest::h5b99ca00c2bca783
  23: 0x772649c4 - rustup::dist::dist::try_update_from_dist_::hf3ecf4073184eaa0
  24: 0x77262587 - rustup::install::InstallMethod::install::hc1e63ca148769e65
  25: 0x77260a7f - rustup::toolchain::DistributableToolchain::install_from_dist::ha25600041b01b912
  26: 0x7734f556 - rustup::cli::self_update::install::h47194fb43e6c8495
  27: 0x76f1bf9e - rustup_init::main::h2d77027039d73808
  28: 0x76f15102 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7b25bcc8e42ab05d
  29: 0x76f1d073 - main
  30: 0x76c70699 - __libc_start_main
rust failed to build: `RUSTFLAGS='-Clto=thin' bash ./rustup.sh -y --no-modify-path --default-host i686-unknown-linux-gnu --default-toolchain stable --profile minimal` exited with 1
```

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #6190 
- Fixes symlinks issue w/ `symlinks` tool usage

Works properly:
- [x] x86_64
- [x] armv7l
- [x] i686

### CODE REVIEW

File: packages/rust.rb [hunk 1]
```diff
@@ -34,7 +34,7 @@ def self.install
     FileUtils.mkdir_p("#{CREW_DEST_PREFIX}/bin")
     FileUtils.mkdir_p("#{CREW_DEST_PREFIX}/share/cargo")
     FileUtils.mkdir_p("#{CREW_DEST_PREFIX}/share/rustup")
-    system "RUSTFLAGS='-Clto=thin' bash ./rustup.sh -y --no-modify-path --default-host #{default_host} --default-toolchain stable --profile minimal"
+    system "RUSTFLAGS='-Clto=thin' bash ./rustup.sh -y --no-modify-path --default-host #{default_host} --default-toolchain #{@_ver} --profile minimal"
```
Comment (uberhacker) [inline packages/rust.rb:37]: Good call.  Does this change the binaries?

File: packages/rust.rb [hunk 2]
```diff
@@ -65,8 +63,13 @@ def self.install
     RUSTCOMPLETIONEOF
     IO.write("#{CREW_DEST_PREFIX}/etc/bash.d/rust", @rustcompletionenv)
     system "#{CREW_DEST_PREFIX}/share/cargo/bin/rustup completions bash > #{CREW_DEST_PREFIX}/share/bash-completion/completions/rustup"
+    Dir.chdir "#{CREW_DEST_PREFIX}/bin" do
+      Dir.glob('*').each do |f|
```
Comment (supechicken) [inline packages/rust.rb:67]: `Dir.glob` can used with block directly:
```ruby
Dir.glob('*') do |f|
```

File: packages/rust.rb [hunk 3]
```diff
@@ -65,8 +63,13 @@ def self.install
...
+        FileUtils.ln_sf "../share/cargo/bin/#{f}", f
+      end
+    end
   end
-  
+
   def self.remove
     config_dirs = %W[#{HOME}/.rustup #{CREW_PREFIX}/share/rustup #{HOME}/.cargo #{CREW_PREFIX}/share/cargo]
     system "echo #{config_dirs}"
```
Comment (supechicken) [inline packages/rust.rb:75]: `puts config_dirs`?

File: packages/rust.rb (hunk 2 above)
Comment (uberhacker) [reply packages/rust.rb:67]: `Dir['*'] do |f|` could work also?  Less is more?

File: packages/rust.rb (hunk 1 above)
Comment (satmandu) [reply packages/rust.rb:37]: Not for 1.55.0, but this will keep the version from being accidentally incremented if installed manually later.

File: packages/rust.rb (hunk 2 above)
Comment (supechicken) [reply packages/rust.rb]: > Dir['*'] do |f| could work also? Less is more?
As I know `Dir[]` doesn't accept block (only arrays)

**Comment by satmandu** [comment]
@uberhacker This was rebuilt, including for i686. Can you see if this works?

**Comment by uberhacker** [comment]
Works in i686.  Nice!
