### PR TITLE
Rebuild gdb, add source_highlight, add texinfo to buildessential

### LINKED ISSUE #5737: gdb fails when called
## Description
Executing the command `gdb` gives an error about an undefined symbol.

If you executed a specific command:
```shell
$ gdb
```

Output:
```shell
gdb: symbol lookup error: gdb: undefined symbol: PyUnicodeUCS2_FromEncodedObject
```

## Versions and system information
chromebrew: `crew --version`
1.9.5

ChromeOS: `cat /etc/lsb-release`
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7259670
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_RELEASE_BOARD=hana-signed-mp-v7keys
CHROMEOS_RELEASE_BRANCH_NUMBER=64
CHROMEOS_RELEASE_BUILDER_PATH=hana-release/R90-13816.64.0
CHROMEOS_RELEASE_BUILD_NUMBER=13816
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=90
CHROMEOS_RELEASE_DESCRIPTION=13816.64.0 (Official Build) stable-channel hana 
CHROMEOS_RELEASE_KEYSET=mp-v7
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=13816.64.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13816.64.0
Model: Lenovo C330

Architecture: `uname -m`
aarch64

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #5737 
- gdb -> 10.2
- Fixed build with `ncursesw`
- Added the `source_highlight` package (arch has it as part of the gdb build).
- Add `texinfo` to `buildessential` (it contains `makeinfo`)

Works properly:
- [x] x86_64
- [x] i686
- [x] armv7l

### CODE REVIEW

**Comment by saltedcoffii** [comment]
I reaaaally don't think combining those is a good idea. We're trying to make packages smaller, not bigger, right?

**Comment by satmandu** [comment]
Combined binutils/gdb:
```
Total found: 413
Disk usage: 46.81MB
```
Separate - just binutils:
```
Total found: 337
Disk usage: 59.96MB
```

In more detail:
```
binutils: The GNU Binutils are a collection of binary tools. This also provides the GNU Debugger.
/usr/local/bin/addr2line
/usr/local/bin/ar
/usr/local/bin/as
/usr/local/bin/c++filt
/usr/local/bin/dwp
/usr/local/bin/elfedit
/usr/local/bin/gcore
/usr/local/bin/gdb
/usr/local/bin/gdb-add-index
/usr/local/bin/gdbserver
/usr/local/bin/gprof
/usr/local/bin/ld
/usr/local/bin/ld.bfd
/usr/local/bin/ld.gold
/usr/local/bin/nm
/usr/local/bin/objcopy
/usr/local/bin/objdump
/usr/local/bin/ranlib
/usr/local/bin/readelf
/usr/local/bin/size
/usr/local/bin/strings
/usr/local/bin/strip
/usr/local/include/ansidecl.h
/usr/local/include/bfd.h
/usr/local/include/bfdlink.h
/usr/local/include/bfd_stdint.h
/usr/local/include/ctf-api.h
/usr/local/include/ctf.h
/usr/local/include/diagnostics.h
/usr/local/include/dis-asm.h
/usr/local/include/gdb/jit-reader.h
/usr/local/include/libiberty/ansidecl.h
/usr/local/include/libiberty/demangle.h
/usr/local/include/libiberty/dyn-string.h
/usr/local/include/libiberty/fibheap.h
/usr/local/include/libiberty/floatformat.h
/usr/local/include/libiberty/hashtab.h
/usr/local/include/libiberty/libiberty.h
/usr/local/include/libiberty/objalloc.h
/usr/local/include/libiberty/partition.h
/usr/local/include/libiberty/safe-ctype.h
/usr/local/include/libiberty/sort.h
/usr/local/include/libiberty/splay-tree.h
/usr/local/include/libiberty/timeval-utils.h
/usr/local/include/plugin-api.h
/usr/local/include/symcat.h
/usr/local/lib64/ldscripts/elf32_x86_64.x
/usr/local/lib64/ldscripts/elf32_x86_64.xbn
/usr/local/lib64/ldscripts/elf32_x86_64.xc
/usr/local/lib64/ldscripts/elf32_x86_64.xce
/usr/local/lib64/ldscripts/elf32_x86_64.xd
/usr/local/lib64/ldscripts/elf32_x86_64.xdc
/usr/local/lib64/ldscripts/elf32_x86_64.xdce
/usr/local/lib64/ldscripts/elf32_x86_64.xde
/usr/local/lib64/ldscripts/elf32_x86_64.xdw
/usr/local/lib64/ldscripts/elf32_x86_64.xdwe
/usr/local/lib64/ldscripts/elf32_x86_64.xe
/usr/local/lib64/ldscripts/elf32_x86_64.xn
/usr/local/lib64/ldscripts/elf32_x86_64.xr
/usr/local/lib64/ldscripts/elf32_x86_64.xs
/usr/local/lib64/ldscripts/elf32_x86_64.xsc
/usr/local/lib64/ldscripts/elf32_x86_64.xsce
/usr/local/lib64/ldscripts/elf32_x86_64.xse
/usr/local/lib64/ldscripts/elf32_x86_64.xsw
/usr/local/lib64/ldscripts/elf32_x86_64.xswe
/usr/local/lib64/ldscripts/elf32_x86_64.xu
/usr/local/lib64/ldscripts/elf32_x86_64.xw
/usr/local/lib64/ldscripts/elf32_x86_64.xwe
/usr/local/lib64/ldscripts/elf_i386.x
/usr/local/lib64/ldscripts/elf_i386.xbn
/usr/local/lib64/ldscripts/elf_i386.xc
/usr/local/lib64/ldscripts/elf_i386.xce
/usr/local/lib64/ldscripts/elf_i386.xd
/usr/local/lib64/ldscripts/elf_i386.xdc
/usr/local/lib64/ldscripts/elf_i386.xdce
/usr/local/lib64/ldscripts/elf_i386.xde
/usr/local/lib64/ldscripts/elf_i386.xdw
/usr/local/lib64/ldscripts/elf_i386.xdwe
/usr/local/lib64/ldscripts/elf_i386.xe
/usr/local/lib64/ldscripts/elf_i386.xn
/usr/local/lib64/ldscripts/elf_i386.xr
/usr/local/lib64/ldscripts/elf_i386.xs
/usr/local/lib64/ldscripts/elf_i386.xsc
/usr/local/lib64/ldscripts/elf_i386.xsce
/usr/local/lib64/ldscripts/elf_i386.xse
/usr/local/lib64/ldscripts/elf_i386.xsw
/usr/local/lib64/ldscripts/elf_i386.xswe
/usr/local/lib64/ldscripts/elf_i386.xu
/usr/local/lib64/ldscripts/elf_i386.xw
/usr/local/lib64/ldscripts/elf_i386.xwe
/usr/local/lib64/ldscripts/elf_iamcu.x
/usr/local/lib64/ldscripts/elf_iamcu.xbn
/usr/local/lib64/ldscripts/elf_iamcu.xc
/usr/local/lib64/ldscripts/elf_iamcu.xce
/usr/local/lib64/ldscripts/elf_iamcu.xd
/usr/local/lib64/ldscripts/elf_iamcu.xdc
/usr/local/lib64/ldscripts/elf_iamcu.xdce
/usr/local/lib64/ldscripts/elf_iamcu.xde
/usr/local/lib64/ldscripts/elf_iamcu.xdw
/usr/local/lib64/ldscripts/elf_iamcu.xdwe
/usr/local/lib64/ldscripts/elf_iamcu.xe
/usr/local/lib64/ldscripts/elf_iamcu.xn
/usr/local/lib64/ldscripts/elf_iamcu.xr
/usr/local/lib64/ldscripts/elf_iamcu.xs
/usr/local/lib64/ldscripts/elf_iamcu.xsc
/usr/local/lib64/ldscripts/elf_iamcu.xsce
/usr/local/lib64/ldscripts/elf_iamcu.xse
/usr/local/lib64/ldscripts/elf_iamcu.xsw
/usr/local/lib64/ldscripts/elf_iamcu.xswe
/usr/local/lib64/ldscripts/elf_iamcu.xu
/usr/local/lib64/ldscripts/elf_iamcu.xw
/usr/local/lib64/ldscripts/elf_iamcu.xwe
/usr/local/lib64/ldscripts/elf_k1om.x
/usr/local/lib64/ldscripts/elf_k1om.xbn
/usr/local/lib64/ldscripts/elf_k1om.xc
/usr/local/lib64/ldscripts/elf_k1om.xce
/usr/local/lib64/ldscripts/elf_k1om.xd
/usr/local/lib64/ldscripts/elf_k1om.xdc
/usr/local/lib64/ldscripts/elf_k1om.xdce
/usr/local/lib64/ldscripts/elf_k1om.xde
/usr/local/lib64/ldscripts/elf_k1om.xdw
/usr/local/lib64/ldscripts/elf_k1om.xdwe
/usr/local/lib64/ldscripts/elf_k1om.xe
/usr/local/lib64/ldscripts/elf_k1om.xn
/usr/local/lib64/ldscripts/elf_k1om.xr
/usr/local/lib64/ldscripts/elf_k1om.xs
/usr/local/lib64/ldscripts/elf_k1om.xsc
/usr/local/lib64/ldscripts/elf_k1om.xsce
/usr/local/lib64/ldscripts/elf_k1om.xse
/usr/local/lib64/ldscripts/elf_k1om.xsw
/usr/local/lib64/ldscripts/elf_k1om.xswe
/usr/local/lib64/ldscripts/elf_k1om.xu
/usr/local/lib64/ldscripts/elf_k1om.xw
/usr/local/lib64/ldscripts/elf_k1om.xwe
/usr/local/lib64/ldscripts/elf_l1om.x
/usr/local/lib64/ldscripts/elf_l1om.xbn
/usr/local/lib64/ldscripts/elf_l1om.xc
/usr/local/lib64/ldscripts/elf_l1om.xce
/usr/local/lib64/ldscripts/elf_l1om.xd
/usr/local/lib64/ldscripts/elf_l1om.xdc
/usr/local/lib64/ldscripts/elf_l1om.xdce
/usr/local/lib64/ldscripts/elf_l1om.xde
/usr/local/lib64/ldscripts/elf_l1om.xdw
/usr/local/lib64/ldscripts/elf_l1om.xdwe
/usr/local/lib64/ldscripts/elf_l1om.xe
/usr/local/lib64/ldscripts/elf_l1om.xn
/usr/local/lib64/ldscripts/elf_l1om.xr
/usr/local/lib64/ldscripts/elf_l1om.xs
/usr/local/lib64/ldscripts/elf_l1om.xsc
/usr/local/lib64/ldscripts/elf_l1om.xsce
/usr/local/lib64/ldscripts/elf_l1om.xse
/usr/local/lib64/ldscripts/elf_l1om.xsw
/usr/local/lib64/ldscripts/elf_l1om.xswe
/usr/local/lib64/ldscripts/elf_l1om.xu
/usr/local/lib64/ldscripts/elf_l1om.xw
/usr/local/lib64/ldscripts/elf_l1om.xwe
/usr/local/lib64/ldscripts/elf_x86_64.x
/usr/local/lib64/ldscripts/elf_x86_64.xbn
/usr/local/lib64/ldscripts/elf_x86_64.xc
/usr/local/lib64/ldscripts/elf_x86_64.xce
/usr/local/lib64/ldscripts/elf_x86_64.xd
/usr/local/lib64/ldscripts/elf_x86_64.xdc
/usr/local/lib64/ldscripts/elf_x86_64.xdce
/usr/local/lib64/ldscripts/elf_x86_64.xde
/usr/local/lib64/ldscripts/elf_x86_64.xdw
/usr/local/lib64/ldscripts/elf_x86_64.xdwe
/usr/local/lib64/ldscripts/elf_x86_64.xe
/usr/local/lib64/ldscripts/elf_x86_64.xn
/usr/local/lib64/ldscripts/elf_x86_64.xr
/usr/local/lib64/ldscripts/elf_x86_64.xs
/usr/local/lib64/ldscripts/elf_x86_64.xsc
/usr/local/lib64/ldscripts/elf_x86_64.xsce
/usr/local/lib64/ldscripts/elf_x86_64.xse
/usr/local/lib64/ldscripts/elf_x86_64.xsw
/usr/local/lib64/ldscripts/elf_x86_64.xswe
/usr/local/lib64/ldscripts/elf_x86_64.xu
/usr/local/lib64/ldscripts/elf_x86_64.xw
/usr/local/lib64/ldscripts/elf_x86_64.xwe
/usr/local/lib64/libbfd-2.35.50.so
/usr/local/lib64/libbfd.a
/usr/local/lib64/libbfd.la
/usr/local/lib64/libbfd.so
/usr/local/lib64/libctf.a
/usr/local/lib64/libctf.la
/usr/local/lib64/libctf-nobfd.a
/usr/local/lib64/libctf-nobfd.la
/usr/local/lib64/libctf-nobfd.so
/usr/local/lib64/libctf-nobfd.so.0
/usr/local/lib64/libctf-nobfd.so.0.0.0
/usr/local/lib64/libctf.so
/usr/local/lib64/libctf.so.0
/usr/local/lib64/libctf.so.0.0.0
/usr/local/lib64/libiberty.a
/usr/local/lib64/libinproctrace.so
/usr/local/lib64/libopcodes-2.35.50.so
/usr/local/lib64/libopcodes.a
/usr/local/lib64/libopcodes.la
/usr/local/lib64/libopcodes.so
/usr/local/share/gdb/python/gdb/command/explore.py
/usr/local/share/gdb/python/gdb/command/frame_filters.py
/usr/local/share/gdb/python/gdb/command/__init__.py
/usr/local/share/gdb/python/gdb/command/pretty_printers.py
/usr/local/share/gdb/python/gdb/command/prompt.py
/usr/local/share/gdb/python/gdb/command/type_printers.py
/usr/local/share/gdb/python/gdb/command/unwinders.py
/usr/local/share/gdb/python/gdb/command/xmethods.py
/usr/local/share/gdb/python/gdb/FrameDecorator.py
/usr/local/share/gdb/python/gdb/FrameIterator.py
/usr/local/share/gdb/python/gdb/frames.py
/usr/local/share/gdb/python/gdb/function/as_string.py
/usr/local/share/gdb/python/gdb/function/caller_is.py
/usr/local/share/gdb/python/gdb/function/__init__.py
/usr/local/share/gdb/python/gdb/function/strfns.py
/usr/local/share/gdb/python/gdb/__init__.py
/usr/local/share/gdb/python/gdb/printer/bound_registers.py
/usr/local/share/gdb/python/gdb/printer/__init__.py
/usr/local/share/gdb/python/gdb/printing.py
/usr/local/share/gdb/python/gdb/prompt.py
/usr/local/share/gdb/python/gdb/types.py
/usr/local/share/gdb/python/gdb/unwinder.py
/usr/local/share/gdb/python/gdb/xmethod.py
/usr/local/share/gdb/syscalls/aarch64-linux.xml
/usr/local/share/gdb/syscalls/amd64-linux.xml
/usr/local/share/gdb/syscalls/arm-linux.xml
/usr/local/share/gdb/syscalls/freebsd.xml
/usr/local/share/gdb/syscalls/gdb-syscalls.dtd
/usr/local/share/gdb/syscalls/i386-linux.xml
/usr/local/share/gdb/syscalls/mips-n32-linux.xml
/usr/local/share/gdb/syscalls/mips-n64-linux.xml
/usr/local/share/gdb/syscalls/mips-o32-linux.xml
/usr/local/share/gdb/syscalls/netbsd.xml
/usr/local/share/gdb/syscalls/ppc64-linux.xml
/usr/local/share/gdb/syscalls/ppc-linux.xml
/usr/local/share/gdb/syscalls/s390-linux.xml
/usr/local/share/gdb/syscalls/s390x-linux.xml
/usr/local/share/gdb/syscalls/sparc64-linux.xml
/usr/local/share/gdb/syscalls/sparc-linux.xml
/usr/local/share/gdb/system-gdbinit/elinos.py
/usr/local/share/gdb/system-gdbinit/wrs-linux.py
/usr/local/share/info/annotate.info.gz
/usr/local/share/info/as.info.gz
/usr/local/share/info/bfd.info.gz
/usr/local/share/info/binutils.info.gz
/usr/local/share/info/gdb.info.gz
/usr/local/share/info/gprof.info.gz
/usr/local/share/info/ld.info.gz
/usr/local/share/info/stabs.info.gz
/usr/local/share/man/man1/addr2line.1.gz
/usr/local/share/man/man1/ar.1.gz
/usr/local/share/man/man1/as.1.gz
/usr/local/share/man/man1/c++filt.1.gz
/usr/local/share/man/man1/dlltool.1.gz
/usr/local/share/man/man1/elfedit.1.gz
/usr/local/share/man/man1/gcore.1.gz
/usr/local/share/man/man1/gdb.1.gz
/usr/local/share/man/man1/gdb-add-index.1.gz
/usr/local/share/man/man1/gdbserver.1.gz
/usr/local/share/man/man1/gprof.1.gz
/usr/local/share/man/man1/ld.1.gz
/usr/local/share/man/man1/nm.1.gz
/usr/local/share/man/man1/objcopy.1.gz
/usr/local/share/man/man1/objdump.1.gz
/usr/local/share/man/man1/ranlib.1.gz
/usr/local/share/man/man1/readelf.1.gz
/usr/local/share/man/man1/size.1.gz
/usr/local/share/man/man1/strings.1.gz
/usr/local/share/man/man1/strip.1.gz
/usr/local/share/man/man1/windmc.1.gz
/usr/local/share/man/man1/windres.1.gz
/usr/local/share/man/man5/gdbinit.5.gz
/usr/local/x86_64-cros-linux-gnu/bin/ar
/usr/local/x86_64-cros-linux-gnu/bin/as
/usr/local/x86_64-cros-linux-gnu/bin/ld
/usr/local/x86_64-cros-linux-gnu/bin/ld.bfd
/usr/local/x86_64-cros-linux-gnu/bin/ld.gold
/usr/local/x86_64-cros-linux-gnu/bin/nm
/usr/local/x86_64-cros-linux-gnu/bin/objcopy
/usr/local/x86_64-cros-linux-gnu/bin/objdump
/usr/local/x86_64-cros-linux-gnu/bin/ranlib
/usr/local/x86_64-cros-linux-gnu/bin/readelf
/usr/local/x86_64-cros-linux-gnu/bin/strip
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.x
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xbn
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xc
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xce
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xd
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xdc
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xdce
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xde
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xdw
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xdwe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xn
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xr
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xs
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xsc
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xsce
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xse
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xsw
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xswe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xu
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xw
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf32_x86_64.xwe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.x
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xbn
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xc
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xce
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xd
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xdc
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xdce
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xde
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xdw
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xdwe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xn
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xr
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xs
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xsc
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xsce
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xse
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xsw
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xswe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xu
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xw
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_i386.xwe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.x
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xbn
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xc
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xce
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xd
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xdc
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xdce
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xde
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xdw
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xdwe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xn
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xr
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xs
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xsc
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xsce
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xse
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xsw
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xswe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xu
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xw
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_iamcu.xwe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.x
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xbn
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xc
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xce
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xd
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xdc
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xdce
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xde
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xdw
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xdwe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xn
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xr
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xs
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xsc
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xsce
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xse
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xsw
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xswe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xu
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xw
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_k1om.xwe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.x
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xbn
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xc
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xce
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xd
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xdc
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xdce
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xde
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xdw
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xdwe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xn
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xr
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xs
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xsc
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xsce
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xse
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xsw
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xswe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xu
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xw
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_l1om.xwe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.x
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xbn
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xc
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xce
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xd
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xdc
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xdce
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xde
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xdw
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xdwe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xn
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xr
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xs
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xsc
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xsce
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xse
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xsw
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xswe
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xu
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xw
/usr/local/x86_64-cros-linux-gnu/lib64/ldscripts/elf_x86_64.xwe
Total found: 413
Disk usage: 46.81MB
```
standalone binutils:
```
binutils: The GNU Binutils are a collection of binary tools.
/usr/local/bin/addr2line
/usr/local/bin/ar
/usr/local/bin/as
/usr/local/bin/c++filt
/usr/local/bin/dwp
/usr/local/bin/elfedit
/usr/local/bin/gprof
/usr/local/bin/ld
/usr/local/bin/ld.bfd
/usr/local/bin/ld.gold
/usr/local/bin/nm
/usr/local/bin/objcopy
/usr/local/bin/objdump
/usr/local/bin/ranlib
/usr/local/bin/readelf
/usr/local/bin/size
/usr/local/bin/strings
/usr/local/bin/strip
/usr/local/include/ansidecl.h
/usr/local/include/bfd.h
/usr/local/include/bfdlink.h
/usr/local/include/bfd_stdint.h
/usr/local/include/ctf-api.h
/usr/local/include/ctf.h
/usr/local/include/diagnostics.h
/usr/local/include/dis-asm.h
/usr/local/include/libiberty/ansidecl.h
/usr/local/include/libiberty/demangle.h
/usr/local/include/libiberty/dyn-string.h
/usr/local/include/libiberty/fibheap.h
/usr/local/include/libiberty/floatformat.h
/usr/local/include/libiberty/hashtab.h
/usr/local/include/libiberty/libiberty.h
/usr/local/include/libiberty/objalloc.h
/usr/local/include/libiberty/partition.h
/usr/local/include/libiberty/safe-ctype.h
/usr/local/include/libiberty/sort.h
/usr/local/include/libiberty/splay-tree.h
/usr/local/include/libiberty/timeval-utils.h
/usr/local/include/plugin-api.h
/usr/local/include/symcat.h
/usr/local/lib64/bfd-plugins/libdep.so
/usr/local/lib64/ldscripts/elf32_x86_64.x
/usr/local/lib64/ldscripts/elf32_x86_64.xbn
/usr/local/lib64/ldscripts/elf32_x86_64.xc
/usr/local/lib64/ldscripts/elf32_x86_64.xce
/usr/local/lib64/ldscripts/elf32_x86_64.xd
/usr/local/lib64/ldscripts/elf32_x86_64.xdc
/usr/local/lib64/ldscripts/elf32_x86_64.xdce
/usr/local/lib64/ldscripts/elf32_x86_64.xde
/usr/local/lib64/ldscripts/elf32_x86_64.xdw
/usr/local/lib64/ldscripts/elf32_x86_64.xdwe
/usr/local/lib64/ldscripts/elf32_x86_64.xe
/usr/local/lib64/ldscripts/elf32_x86_64.xn
/usr/local/lib64/ldscripts/elf32_x86_64.xr
/usr/local/lib64/ldscripts/elf32_x86_64.xs
/usr/local/lib64/ldscripts/elf32_x86_64.xsc
/usr/local/lib64/ldscripts/elf32_x86_64.xsce
/usr/local/lib64/ldscripts/elf32_x86_64.xse
/usr/local/lib64/ldscripts/elf32_x86_64.xsw
/usr/local/lib64/ldscripts/elf32_x86_64.xswe
/usr/local/lib64/ldscripts/elf32_x86_64.xu
/usr/local/lib64/ldscripts/elf32_x86_64.xw
/usr/local/lib64/ldscripts/elf32_x86_64.xwe
/usr/local/lib64/ldscripts/elf_i386.x
/usr/local/lib64/ldscripts/elf_i386.xbn
/usr/local/lib64/ldscripts/elf_i386.xc
/usr/local/lib64/ldscripts/elf_i386.xce
/usr/local/lib64/ldscripts/elf_i386.xd
/usr/local/lib64/ldscripts/elf_i386.xdc
/usr/local/lib64/ldscripts/elf_i386.xdce
/usr/local/lib64/ldscripts/elf_i386.xde
/usr/local/lib64/ldscripts/elf_i386.xdw
/usr/local/lib64/ldscripts/elf_i386.xdwe
/usr/local/lib64/ldscripts/elf_i386.xe
/usr/local/lib64/ldscripts/elf_i386.xn
/usr/local/lib64/ldscripts/elf_i386.xr
/usr/local/lib64/ldscripts/elf_i386.xs
/usr/local/lib64/ldscripts/elf_i386.xsc
/usr/local/lib64/ldscripts/elf_i386.xsce
/usr/local/lib64/ldscripts/elf_i386.xse
/usr/local/lib64/ldscripts/elf_i386.xsw
/usr/local/lib64/ldscripts/elf_i386.xswe
/usr/local/lib64/ldscripts/elf_i386.xu
/usr/local/lib64/ldscripts/elf_i386.xw
/usr/local/lib64/ldscripts/elf_i386.xwe
/usr/local/lib64/ldscripts/elf_iamcu.x
/usr/local/lib64/ldscripts/elf_iamcu.xbn
/usr/local/lib64/ldscripts/elf_iamcu.xc
/usr/local/lib64/ldscripts/elf_iamcu.xce
/usr/local/lib64/ldscripts/elf_iamcu.xd
/usr/local/lib64/ldscripts/elf_iamcu.xdc
/usr/local/lib64/ldscripts/elf_iamcu.xdce
/usr/local/lib64/ldscripts/elf_iamcu.xde
/usr/local/lib64/ldscripts/elf_iamcu.xdw
/usr/local/lib64/ldscripts/elf_iamcu.xdwe
/usr/local/lib64/ldscripts/elf_iamcu.xe
/usr/local/lib64/ldscripts/elf_iamcu.xn
/usr/local/lib64/ldscripts/elf_iamcu.xr
/usr/local/lib64/ldscripts/elf_iamcu.xs
/usr/local/lib64/ldscripts/elf_iamcu.xsc
/usr/local/lib64/ldscripts/elf_iamcu.xsce
/usr/local/lib64/ldscripts/elf_iamcu.xse
/usr/local/lib64/ldscripts/elf_iamcu.xsw
/usr/local/lib64/ldscripts/elf_iamcu.xswe
/usr/local/lib64/ldscripts/elf_iamcu.xu
/usr/local/lib64/ldscripts/elf_iamcu.xw
/usr/local/lib64/ldscripts/elf_iamcu.xwe
/usr/local/lib64/ldscripts/elf_k1om.x
/usr/local/lib64/ldscripts/elf_k1om.xbn
/usr/local/lib64/ldscripts/elf_k1om.xc
/usr/local/lib64/ldscripts/elf_k1om.xce
/usr/local/lib64/ldscripts/elf_k1om.xd
/usr/local/lib64/ldscripts/elf_k1om.xdc
/usr/local/lib64/ldscripts/elf_k1om.xdce
/usr/local/lib64/ldscripts/elf_k1om.xde
/usr/local/lib64/ldscripts/elf_k1om.xdw
/usr/local/lib64/ldscripts/elf_k1om.xdwe
/usr/local/lib64/ldscripts/elf_k1om.xe
/usr/local/lib64/ldscripts/elf_k1om.xn
/usr/local/lib64/ldscripts/elf_k1om.xr
/usr/local/lib64/ldscripts/elf_k1om.xs
/usr/local/lib64/ldscripts/elf_k1om.xsc
/usr/local/lib64/ldscripts/elf_k1om.xsce
/usr/local/lib64/ldscripts/elf_k1om.xse
/usr/local/lib64/ldscripts/elf_k1om.xsw
/usr/local/lib64/ldscripts/elf_k1om.xswe
/usr/local/lib64/ldscripts/elf_k1om.xu
/usr/local/lib64/ldscripts/elf_k1om.xw
/usr/local/lib64/ldscripts/elf_k1om.xwe
/usr/local/lib64/ldscripts/elf_l1om.x
/usr/local/lib64/ldscripts/elf_l1om.xbn
/usr/local/lib64/ldscripts/elf_l1om.xc
/usr/local/lib64/ldscripts/elf_l1om.xce
/usr/local/lib64/ldscripts/elf_l1om.xd
/usr/local/lib64/ldscripts/elf_l1om.xdc
/usr/local/lib64/ldscripts/elf_l1om.xdce
/usr/local/lib64/ldscripts/elf_l1om.xde
/usr/local/lib64/ldscripts/elf_l1om.xdw
/usr/local/lib64/ldscripts/elf_l1om.xdwe
/usr/local/lib64/ldscripts/elf_l1om.xe
/usr/local/lib64/ldscripts/elf_l1om.xn
/usr/local/lib64/ldscripts/elf_l1om.xr
/usr/local/lib64/ldscripts/elf_l1om.xs
/usr/local/lib64/ldscripts/elf_l1om.xsc
/usr/local/lib64/ldscripts/elf_l1om.xsce
/usr/local/lib64/ldscripts/elf_l1om.xse
/usr/local/lib64/ldscripts/elf_l1om.xsw
/usr/local/lib64/ldscripts/elf_l1om.xswe
/usr/local/lib64/ldscripts/elf_l1om.xu
/usr/local/lib64/ldscripts/elf_l1om.xw
/usr/local/lib64/ldscripts/elf_l1om.xwe
/usr/local/lib64/ldscripts/elf_x86_64.x
/usr/local/lib64/ldscripts/elf_x86_64.xbn
/usr/local/lib64/ldscripts/elf_x86_64.xc
/usr/local/lib64/ldscripts/elf_x86_64.xce
/usr/local/lib64/ldscripts/elf_x86_64.xd
/usr/local/lib64/ldscripts/elf_x86_64.xdc
/usr/local/lib64/ldscripts/elf_x86_64.xdce
/usr/local/lib64/ldscripts/elf_x86_64.xde
/usr/local/lib64/ldscripts/elf_x86_64.xdw
/usr/local/lib64/ldscripts/elf_x86_64.xdwe
/usr/local/lib64/ldscripts/elf_x86_64.xe
/usr/local/lib64/ldscripts/elf_x86_64.xn
/usr/local/lib64/ldscripts/elf_x86_64.xr
/usr/local/lib64/ldscripts/elf_x86_64.xs
/usr/local/lib64/ldscripts/elf_x86_64.xsc
/usr/local/lib64/ldscripts/elf_x86_64.xsce
/usr/local/lib64/ldscripts/elf_x86_64.xse
/usr/local/lib64/ldscripts/elf_x86_64.xsw
/usr/local/lib64/ldscripts/elf_x86_64.xswe
/usr/local/lib64/ldscripts/elf_x86_64.xu
/usr/local/lib64/ldscripts/elf_x86_64.xw
/usr/local/lib64/ldscripts/elf_x86_64.xwe
/usr/local/lib64/libbfd-2.36.1.so
/usr/local/lib64/libbfd.a
/usr/local/lib64/libbfd.la
/usr/local/lib64/libbfd.so
/usr/local/lib64/libctf.a
/usr/local/lib64/libctf.la
/usr/local/lib64/libctf-nobfd.a
/usr/local/lib64/libctf-nobfd.la
/usr/local/lib64/libctf-nobfd.so
/usr/local/lib64/libctf-nobfd.so.0
/usr/local/lib64/libctf-nobfd.so.0.0.0
/usr/local/lib64/libctf.so
/usr/local/lib64/libctf.so.0
/usr/local/lib64/libctf.so.0.0.0
/usr/local/lib64/libiberty.a
/usr/local/lib64/libopcodes-2.36.1.so
/usr/local/lib64/libopcodes.a
/usr/local/lib64/libopcodes.la
/usr/local/lib64/libopcodes.so
/usr/local/lib/bfd-plugins
/usr/local/share/info/as.info.gz
/usr/local/share/info/bfd.info.gz
/usr/local/share/info/binutils.info.gz
/usr/local/share/info/gprof.info.gz
/usr/local/share/info/ld.info.gz
/usr/local/share/locale/bg/LC_MESSAGES/binutils.mo
/usr/local/share/locale/bg/LC_MESSAGES/gprof.mo
/usr/local/share/locale/bg/LC_MESSAGES/ld.mo
/usr/local/share/locale/ca/LC_MESSAGES/binutils.mo
/usr/local/share/locale/da/LC_MESSAGES/bfd.mo
/usr/local/share/locale/da/LC_MESSAGES/binutils.mo
/usr/local/share/locale/da/LC_MESSAGES/gprof.mo
/usr/local/share/locale/da/LC_MESSAGES/ld.mo
/usr/local/share/locale/da/LC_MESSAGES/opcodes.mo
/usr/local/share/locale/de/LC_MESSAGES/gprof.mo
/usr/local/share/locale/de/LC_MESSAGES/ld.mo
/usr/local/share/locale/de/LC_MESSAGES/opcodes.mo
/usr/local/share/locale/eo/LC_MESSAGES/gprof.mo
/usr/local/share/locale/es/LC_MESSAGES/bfd.mo
/usr/local/share/locale/es/LC_MESSAGES/binutils.mo
/usr/local/share/locale/es/LC_MESSAGES/gas.mo
/usr/local/share/locale/es/LC_MESSAGES/gold.mo
/usr/local/share/locale/es/LC_MESSAGES/gprof.mo
/usr/local/share/locale/es/LC_MESSAGES/ld.mo
/usr/local/share/locale/es/LC_MESSAGES/opcodes.mo
/usr/local/share/locale/fi/LC_MESSAGES/bfd.mo
/usr/local/share/locale/fi/LC_MESSAGES/binutils.mo
/usr/local/share/locale/fi/LC_MESSAGES/gas.mo
/usr/local/share/locale/fi/LC_MESSAGES/gold.mo
/usr/local/share/locale/fi/LC_MESSAGES/gprof.mo
/usr/local/share/locale/fi/LC_MESSAGES/ld.mo
/usr/local/share/locale/fi/LC_MESSAGES/opcodes.mo
/usr/local/share/locale/fr/LC_MESSAGES/bfd.mo
/usr/local/share/locale/fr/LC_MESSAGES/binutils.mo
/usr/local/share/locale/fr/LC_MESSAGES/gas.mo
/usr/local/share/locale/fr/LC_MESSAGES/gold.mo
/usr/local/share/locale/fr/LC_MESSAGES/gprof.mo
/usr/local/share/locale/fr/LC_MESSAGES/ld.mo
/usr/local/share/locale/fr/LC_MESSAGES/opcodes.mo
/usr/local/share/locale/ga/LC_MESSAGES/gprof.mo
/usr/local/share/locale/ga/LC_MESSAGES/ld.mo
/usr/local/share/locale/ga/LC_MESSAGES/opcodes.mo
/usr/local/share/locale/hr/LC_MESSAGES/bfd.mo
/usr/local/share/locale/hr/LC_MESSAGES/binutils.mo
/usr/local/share/locale/hu/LC_MESSAGES/gprof.mo
/usr/local/share/locale/id/LC_MESSAGES/bfd.mo
/usr/local/share/locale/id/LC_MESSAGES/binutils.mo
/usr/local/share/locale/id/LC_MESSAGES/gas.mo
/usr/local/share/locale/id/LC_MESSAGES/gold.mo
/usr/local/share/locale/id/LC_MESSAGES/gprof.mo
/usr/local/share/locale/id/LC_MESSAGES/ld.mo
/usr/local/share/locale/id/LC_MESSAGES/opcodes.mo
/usr/local/share/locale/it/LC_MESSAGES/binutils.mo
/usr/local/share/locale/it/LC_MESSAGES/gold.mo
/usr/local/share/locale/it/LC_MESSAGES/gprof.mo
/usr/local/share/locale/it/LC_MESSAGES/ld.mo
/usr/local/share/locale/it/LC_MESSAGES/opcodes.mo
/usr/local/share/locale/ja/LC_MESSAGES/bfd.mo
/usr/local/share/locale/ja/LC_MESSAGES/binutils.mo
/usr/local/share/locale/ja/LC_MESSAGES/gas.mo
/usr/local/share/locale/ja/LC_MESSAGES/gold.mo
/usr/local/share/locale/ja/LC_MESSAGES/gprof.mo
/usr/local/share/locale/ja/LC_MESSAGES/ld.mo
/usr/local/share/locale/ms/LC_MESSAGES/gprof.mo
/usr/local/share/locale/nl/LC_MESSAGES/gprof.mo
/usr/local/share/locale/nl/LC_MESSAGES/opcodes.mo
/usr/local/share/locale/pt_BR/LC_MESSAGES/gprof.mo
/usr/local/share/locale/pt_BR/LC_MESSAGES/ld.mo
/usr/local/share/locale/pt_BR/LC_MESSAGES/opcodes.mo
/usr/local/share/locale/pt/LC_MESSAGES/bfd.mo
/usr/local/share/locale/pt/LC_MESSAGES/binutils.mo
/usr/local/share/locale/ro/LC_MESSAGES/bfd.mo
/usr/local/share/locale/ro/LC_MESSAGES/binutils.mo
/usr/local/share/locale/ro/LC_MESSAGES/gprof.mo
/usr/local/share/locale/ro/LC_MESSAGES/opcodes.mo
/usr/local/share/locale/ru/LC_MESSAGES/bfd.mo
/usr/local/share/locale/ru/LC_MESSAGES/binutils.mo
/usr/local/share/locale/ru/LC_MESSAGES/gas.mo
/usr/local/share/locale/ru/LC_MESSAGES/gprof.mo
/usr/local/share/locale/ru/LC_MESSAGES/ld.mo
/usr/local/share/locale/rw/LC_MESSAGES/bfd.mo
/usr/local/share/locale/rw/LC_MESSAGES/binutils.mo
/usr/local/share/locale/rw/LC_MESSAGES/gas.mo
/usr/local/share/locale/rw/LC_MESSAGES/gprof.mo
/usr/local/share/locale/sk/LC_MESSAGES/binutils.mo
/usr/local/share/locale/sr/LC_MESSAGES/bfd.mo
/usr/local/share/locale/sr/LC_MESSAGES/binutils.mo
/usr/local/share/locale/sr/LC_MESSAGES/gold.mo
/usr/local/share/locale/sr/LC_MESSAGES/gprof.mo
/usr/local/share/locale/sr/LC_MESSAGES/ld.mo
/usr/local/share/locale/sr/LC_MESSAGES/opcodes.mo
/usr/local/share/locale/sv/LC_MESSAGES/bfd.mo
/usr/local/share/locale/sv/LC_MESSAGES/binutils.mo
/usr/local/share/locale/sv/LC_MESSAGES/gas.mo
/usr/local/share/locale/sv/LC_MESSAGES/gold.mo
/usr/local/share/locale/sv/LC_MESSAGES/gprof.mo
/usr/local/share/locale/sv/LC_MESSAGES/ld.mo
/usr/local/share/locale/sv/LC_MESSAGES/opcodes.mo
/usr/local/share/locale/tr/LC_MESSAGES/bfd.mo
/usr/local/share/locale/tr/LC_MESSAGES/binutils.mo
/usr/local/share/locale/tr/LC_MESSAGES/gas.mo
/usr/local/share/locale/tr/LC_MESSAGES/gprof.mo
/usr/local/share/locale/tr/LC_MESSAGES/ld.mo
/usr/local/share/locale/tr/LC_MESSAGES/opcodes.mo
/usr/local/share/locale/uk/LC_MESSAGES/bfd.mo
/usr/local/share/locale/uk/LC_MESSAGES/binutils.mo
/usr/local/share/locale/uk/LC_MESSAGES/gas.mo
/usr/local/share/locale/uk/LC_MESSAGES/gold.mo
/usr/local/share/locale/uk/LC_MESSAGES/gprof.mo
/usr/local/share/locale/uk/LC_MESSAGES/ld.mo
/usr/local/share/locale/uk/LC_MESSAGES/opcodes.mo
/usr/local/share/locale/vi/LC_MESSAGES/bfd.mo
/usr/local/share/locale/vi/LC_MESSAGES/binutils.mo
/usr/local/share/locale/vi/LC_MESSAGES/gold.mo
/usr/local/share/locale/vi/LC_MESSAGES/gprof.mo
/usr/local/share/locale/vi/LC_MESSAGES/ld.mo
/usr/local/share/locale/vi/LC_MESSAGES/opcodes.mo
/usr/local/share/locale/zh_CN/LC_MESSAGES/bfd.mo
/usr/local/share/locale/zh_CN/LC_MESSAGES/binutils.mo
/usr/local/share/locale/zh_CN/LC_MESSAGES/gas.mo
/usr/local/share/locale/zh_CN/LC_MESSAGES/gold.mo
/usr/local/share/locale/zh_CN/LC_MESSAGES/ld.mo
/usr/local/share/locale/zh_CN/LC_MESSAGES/opcodes.mo
/usr/local/share/locale/zh_TW/LC_MESSAGES/binutils.mo
/usr/local/share/locale/zh_TW/LC_MESSAGES/ld.mo
/usr/local/share/man/man1/addr2line.1.gz
/usr/local/share/man/man1/ar.1.gz
/usr/local/share/man/man1/as.1.gz
/usr/local/share/man/man1/c++filt.1.gz
/usr/local/share/man/man1/dlltool.1.gz
/usr/local/share/man/man1/elfedit.1.gz
/usr/local/share/man/man1/gprof.1.gz
/usr/local/share/man/man1/ld.1.gz
/usr/local/share/man/man1/nm.1.gz
/usr/local/share/man/man1/objcopy.1.gz
/usr/local/share/man/man1/objdump.1.gz
/usr/local/share/man/man1/ranlib.1.gz
/usr/local/share/man/man1/readelf.1.gz
/usr/local/share/man/man1/size.1.gz
/usr/local/share/man/man1/strings.1.gz
/usr/local/share/man/man1/strip.1.gz
/usr/local/share/man/man1/windmc.1.gz
/usr/local/share/man/man1/windres.1.gz
Total found: 337
Disk usage: 59.96MB
```

(Having said that, I'm dropping this back to draft as I want to do more testing...)

File: packages/binutils.rb [hunk 1]
```diff
@@ -70,8 +93,16 @@ def self.check
...
+      system 'make', "DESTDIR=#{CREW_DEST_DIR}", 'install'
       system 'make', "DESTDIR=#{CREW_DEST_DIR}", "prefix=#{CREW_PREFIX}",
              "tooldir=#{CREW_PREFIX}", 'install'
     end
   end
+
+  def self.postinstall
+    puts
+    puts 'To use gdb, please install the gdb runtime dependencies with:'.lightblue
+    puts 'crew install gdb'.lightblue
```
Comment (uberhacker) [inline packages/binutils.rb:105]: Wait..what?  The description now says `This also provides the GNU Debugger` but we still need to install gdb?

File: packages/source_highlight.rb [hunk 2]
```diff
@@ -0,0 +1,47 @@
+# Adapted from Arch Linux source-highlight PKGBUILD at:
+# https://github.com/archlinux/svntogit-packages/raw/packages/source-highlight/trunk/PKGBUILD
+
+require 'package'
+
+class Source_highlight < Package
+  description 'Convert source code to syntax highlighted document'
+  homepage 'https://www.gnu.org/software/src-highlite/'
+  version '3.1.9-9049'
+  license 'GPL'
```
Comment (uberhacker) [inline packages/source_highlight.rb:10]: Shouldn't we also supply the version?

File: packages/binutils.rb (hunk 1 above)
Comment (satmandu) [reply packages/binutils.rb:105]: I moved the gdb dependencies into a separate package, so gdb is only really functional with that package, as it installs those dependencies. Should I just not mention gdb in this package description at all?

File: packages/source_highlight.rb (hunk 2 above)
Comment (satmandu) [reply packages/source_highlight.rb:10]: That's a mix of version from the source plus hash...

File: packages/binutils.rb (hunk 1 above)
Comment (uberhacker) [reply packages/binutils.rb:105]: Maybe should remove because it's confusing.

**Comment by satmandu** [comment]
I'm going to split these up again. Since gdb and binutils are on different release schedules, it seems prudent to keep them separate. (Also I'm having subtle compilation issues and that's obviously a huge no-no.)

File: packages/binutils.rb (hunk 1 above)
Comment (satmandu) [reply packages/binutils.rb]: irrelevant now due to splitting packages again...

**Comment by satmandu** [comment]
ok this should be good to go. It really only fixes gdb...
