### PR TITLE
[ctags] Fix installation problem

### LINKED ISSUE #2048: [ctags] no binary installed
chronos@localhost ~/Downloads $ crew install ctags && crew files ctags && crew remove ctags
ctags: Exuberant Ctags is a multilanguage reimplementation of the Unix ctags utility.
https://sourceforge.net/projects/ctags/
version 5.8
Precompiled binary available, downloading...
Archive downloaded
Unpacking archive, this may take awhile...
Installing...
tar: ./usr/*: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
Performing post-install...
Ctags installed!
(i) ctags: Exuberant Ctags is a multilanguage reimplementation of the Unix ctags utility.
https://sourceforge.net/projects/ctags/
version 5.8
Total found: 0
Ctags removed!

### PR DESCRIPTION
**Pull request by lovedheart**
Fix #2048

### CODE REVIEW

File: packages/ctags.rb [hunk 1]
```diff
@@ -8,24 +8,24 @@ class Ctags < Package
...
-       i686: '21fd5f780112b4e7d7df6c5d8cdc5c10e5507b4e597a071b332e9d30efa40ebe',
-     x86_64: 'd3003d8b2e138bb774b119d089aa8de6c5d5881dc6229a89149bb974ce8a20a4',
+
   })
 
   def self.build
-    system "./configure"
-    system "make"
+   system "./configure --prefix=#{CREW_PREFIX} --libdir=#{CREW_LIB_PREFIX}"
+   system "make"
```
Comment (uberhacker) [inline packages/ctags.rb]: Please use proper 2 space indentation.

File: packages/ctags.rb [hunk 2]
```diff
@@ -8,24 +8,24 @@ class Ctags < Package
...
   end
 
   def self.install
-    system "make", "DESTDIR=#{CREW_DEST_DIR}", "install"
+    #system "make", "DESTDIR=#{CREW_DEST_DIR}", "install"  # it does not work here
+    `mkdir -p #{CREW_DEST_PREFIX}/bin`
```
Comment (uberhacker) [inline packages/ctags.rb]: This is an interesting way to execute system commands.

File: packages/ctags.rb [hunk 3]
```diff
@@ -8,24 +8,24 @@ class Ctags < Package
...
+    `cp ctags #{CREW_DEST_PREFIX}/bin/ctags`
+    `chmod 755 #{CREW_DEST_PREFIX}/bin/ctags`
```
Comment (uberhacker) [inline packages/ctags.rb]: You can replace the 3 lines above with a single line:
```
system "install -D755 ctags #{CREW_DEST_PREFIX}/bin/ctags"
```

File: packages/ctags.rb [hunk 4]
```diff
@@ -8,24 +8,24 @@ class Ctags < Package
...
+    `mkdir -p #{CREW_DEST_PREFIX}/share/man/man1`
+    `cp ./ctags.1 #{CREW_DEST_PREFIX}/share/man/man1/ctags.1`
+    `chmod 644 #{CREW_DEST_PREFIX}/share/man/man1/ctags.1`
```
Comment (uberhacker) [inline packages/ctags.rb]: Can we gzip this man page? You can also replace the mkdir, cp and chmod lines with a single command:
```
system "gzip -9 ctags.1"
system "install -D644 ctags.1.gz #{CREW_DEST_PREFIX}/share/man/man1/ctags.1.gz"
```

File: packages/ctags.rb [hunk 5]
```diff
@@ -8,24 +8,24 @@ class Ctags < Package
...
-     x86_64: 'https://dl.bintray.com/chromebrew/chromebrew/ctags-5.8-chromeos-x86_64.tar.xz',
+
   })
   binary_sha256 ({
-    aarch64: '81a6e5cf24475c276751966ab9ccd884fa7fb339e7c2b6224a928fe9a130bec7',
-     armv7l: '81a6e5cf24475c276751966ab9ccd884fa7fb339e7c2b6224a928fe9a130bec7',
-       i686: '21fd5f780112b4e7d7df6c5d8cdc5c10e5507b4e597a071b332e9d30efa40ebe',
-     x86_64: 'd3003d8b2e138bb774b119d089aa8de6c5d5881dc6229a89149bb974ce8a20a4',
+
   })
```
Comment (uberhacker) [inline packages/ctags.rb]: It might be easier just to remove all these lines including the `binary_url ({` and `binary_sha256 ({` lines.  I can easily replace when generating the pre-built binaries.

**Comment by uberhacker** [comment]
Thank you for the update @lovedheart!  Can we please bump the version also?

**Comment by uberhacker** [comment]
Bump version?
