### PR TITLE
elogind: Add binaries

### LINKED ISSUE #5229: [elogind] Failed to build
```
[39/369] Compiling C object src/basic/libbasic.a.p/btrfs-util.c.o
FAILED: src/basic/libbasic.a.p/btrfs-util.c.o 
cc -Isrc/basic/libbasic.a.p -Isrc/basic -I../src/basic -I../src/boot -Isrc/shared -I../src/shared -Isrc/systemd -I../src/systemd -Isrc/journal -I../src/journal -Isrc/login -I../src/login -Isrc/core -I../src/core -I../src/libelogind/sd-bus -I../src/libelogind/sd-device -I../src/libelogind/sd-event -I../src/libelogind/sd-hwdb -I../src/libelogind/sd-id128 -Isrc/sleep -I../src/sleep -Isrc/update-utmp -I../src/update-utmp -I. -I.. -flto=auto -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu99 -O3 -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -ffunction-sections -fdata-sections -Werror=shadow -include config.h -fuse-ld=gold -fPIC -pthread -fvisibility=default -MD -MQ src/basic/libbasic.a.p/btrfs-util.c.o -MF src/basic/libbasic.a.p/btrfs-util.c.o.d -o src/basic/libbasic.a.p/btrfs-util.c.o -c ../src/basic/btrfs-util.c
../src/basic/btrfs-util.c:6:10: fatal error: linux/btrfs_tree.h: No such file or directory
    6 | #include <linux/btrfs_tree.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
[40/369] Compiling C object src/basic/libbasic.a.p/blockdev-util.c.o
[41/369] Compiling C object src/libelogind/libelogind_static.a.p/sd-bus_bus-objects.c.o
[42/369] Compiling C object src/basic/libbasic.a.p/cgroup-util.c.o
[43/369] Compiling C object src/basic/libbasic.a.p/bus-label.c.o
[44/369] Compiling C object src/libelogind/libelogind_static.a.p/sd-bus_bus-message.c.o
ninja: build stopped: subcommand failed.
elogind failed to build: `ninja -C builddir` exited with 1
```

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #5229

Compiles properly:
- [x] x86_64
- [x] armv7l
- [x] i686

### CODE REVIEW

File: packages/elogind.rb [hunk 1]
```diff
@@ -3,11 +3,24 @@
 class Elogind < Package
   description 'Standalone systemd-logind fork'
   homepage 'https://github.com/elogind/elogind'
-  version '246.9.2'
+  version '246.9.2-4c20'
```
Comment (uberhacker) [inline packages/elogind.rb:6]: Included in the latest release? https://github.com/elogind/elogind/releases/tag/v246.10

Comment (satmandu) [reply packages/elogind.rb:6]: Rebuilding...

Comment (satmandu) [reply packages/elogind.rb]: Done.
