### PR TITLE
`lib/downloader.rb`: Fix redirection for URL without hostname provided

### LINKED ISSUE #6631: Issue with downloader not downloading
image

```
chronos@localhost /usr/local/lib/crew/packages (master %|SPARSE=)$ crew const | grep CURL
CURL=curl
```
This works though:
```
chronos@localhost /usr/local/lib/crew/packages (master %|SPARSE=)$ CURL=/usr/local/bin/curl crew install chrome
chrome: Google Chrome is a fast, easy to use, and secure web browser.
https://www.google.com/chrome
Version: 97.0.4692.71-1
License: google-chrome
Performing pre-flight checks...
No precompiled binary available for your platform, downloading source...
########################################################################################### 100.0%
Chrome archive downloaded.
```
Thoughts @supechicken ?

### PR DESCRIPTION
**Pull request by supechicken**
Fixes #6631

See https://github.com/skycocker/chromebrew/issues/6631#issuecomment-1015006488 for more info.

Tested on `x86_64`

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/supechicken/chromebrew.git CREW_TESTING_BRANCH=downloader_fix CREW_TESTING=1 crew update
```

### CODE REVIEW

File: lib/downloader.rb [hunk 1]
```diff
@@ -66,7 +66,12 @@ def downloader (url, filename = File.basename(url), retry_count = 0, verbose = f
           * Follow HTTP redirection: #{response['Location']}
           *
         EOT
-        return downloader(response['Location'], filename, retry_count, verbose)
+
+        redirect_uri = URI(response['Location'])
+        redirect_uri.scheme ||= uri.scheme
+        redirect_uri.host ||= uri.host
+
+        return downloader(redirect_uri.to_s, filename, retry_count, verbose)
```
Comment (uberhacker) [inline lib/downloader.rb:74]: Does the `.to_s` conversion work?  We're talking about an object converted to a string?
