### PR TITLE
qemu -> 6.2.0

### LINKED ISSUE #6536: Unable to Install QEMU - Noob sorry
Hey guys just trying to install the android subsystem into cloud ready but hit a snag installing qemu, says that c doesn't exist?
Tried reinstalling gcc but no dice

chronos@localhost /usr/local/tmp/libepoxy-1.5.5 $ crew reinstall gcc
gcc: The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Ada, and Go.
Removing since upgrade or reinstall...
Gcc removed!
Performing post-install for gcc...
Gcc installed!
chronos@localhost /usr/local/tmp/libepoxy-1.5.5 $ crew install qemu
qemu: QEMU is a generic and open source machine emulator and virtualizer.
http://www.qemu.org/
Version: 4.2.0
License: GPL-2, LGPL-2 and BSD-2
Performing pre-flight checks...
No precompiled binary available for your platform, downloading source...
[##############################################################################################################################################################]  59.34 MB 100%
Qemu archive downloaded.
Unpacking archive using 'tar', this may take a while...
Building from source, this may take a while...
Rename all *.la files to *.la_tmp

ERROR: "cc" either does not exist or does not work

qemu failed to install: `./configure --prefix=/usr/local --libdir=/usr/local/lib64 --disable-stack-protector` exited with 1
chronos@localhost /usr/local/tmp/libepoxy-1.5.5 $

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #6536 

Works properly:
- [x] x86_64
- [x] armv7l
- [ ] i686 (will not build, but that's fine. We don't need qemu for i686.)

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=qemu CREW_TESTING=1 crew update
```

### CODE REVIEW

File: packages/qemu.rb [hunk 1]
```diff
@@ -31,14 +33,18 @@ class Qemu < Package
...
 
   def self.build
-    system './configure',
-           "--prefix=#{CREW_PREFIX}",
-           "--libdir=#{CREW_LIB_PREFIX}",
-           "--disable-stack-protector"
-    system 'make'
+    FileUtils.mkdir_p 'build'
+    Dir.chdir 'build' do
+      system "#{CREW_ENV_OPTIONS} ../configure #{CREW_OPTIONS.sub(/--target.*/, '')} \
```
Comment (supechicken) [inline packages/qemu.rb:38]: Use `meson`?

Comment (uberhacker) [reply packages/qemu.rb:38]: I don't think you understand what it means to ask @satmandu to compile this all over again. :)

**Comment by satmandu** [comment]
FYI qemu uses meson internally, but it needs to be configured using the
configure script...

**Comment by satmandu** [comment]
Also @supechicken this build on `armv7l` took almost 3 days...
