### PR TITLE
Fonts package updates (w/o reworking crew) + qemu -> 7.0 (also update qemu deps)

### LINKED ISSUE #6959: [qemu] Incorrect libpng library version
```
$ crew search ^qemu -v
qemu: QEMU is a generic and open source machine emulator and virtualizer.
http://www.qemu.org/
Version: 6.2.0
$ qemu-system-x86_64
qemu-system-x86_64: /usr/local/lib64/libpng16.so.16: version `PNG16_0' not found (required by qemu-system-x86_64)
```

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #6959 

- Also `qemu`->7.0

Works properly:
- [x] `x86_64`
- [x] `i686`
- [x] `armv7l` 

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=fonts3 CREW_TESTING=1 crew update
crew upgrade pixman fontconfig harfbuzz librsvg freetype cairo glib libxdmcp
```

### CODE REVIEW

File: packages/freetype.rb [hunk 1]
```diff
@@ -62,5 +56,29 @@ def self.install
...
+      end
+      conflicts.each do |conflict|
+        conflict.each do |thisconflict|
+          singleconflict = thisconflict.split(':',-1)
+          if @override_allowed.include?(singleconflict[0])
+            system "sed -i '\\\?^#{singleconflict[1]}?d'  #{CREW_META_PATH}/#{singleconflict[0]}.filelist"
+          end
+        end
+      end
+    end
```
Comment (uberhacker) [inline packages/freetype.rb:82]: Should this logic replace the conflict handling code we have in crew?  Seems like it could be used universally?

File: packages/harfbuzz.rb [hunk 2]
```diff
@@ -64,4 +67,39 @@ def self.build
...
+      conflicts.each do |conflict|
+        conflict.each do |thisconflict|
+          singleconflict = thisconflict.split(':',-1)
+          if @override_allowed.include?(singleconflict[0])
+            system "sed -i '\\\?^#{singleconflict[1]}?d'  #{CREW_META_PATH}/#{singleconflict[0]}.filelist"
+          end
+        end
+      end
+    end
+  end
```
Comment (uberhacker) [inline packages/harfbuzz.rb:104]: Should this logic replace the conflict handling code we have in crew? Seems like it could be used universally?

File: packages/freetype.rb (hunk 1 above)
Comment (satmandu) [reply packages/freetype.rb:82]: I think this function should ultimately be integrated into crew, yes.

But I was waiting on @supechicken 's work on making packages smaller in https://github.com/supechicken/chromebrew/tree/llvm_lib_diff to get done, but I haven't had time to go through that yet.

Comment (uberhacker) [reply packages/freetype.rb:82]: Does this logic override what crew executes or does it run afterwards?  I'm guessing there are 2 conflicts checks running?

Comment (uberhacker) [reply packages/freetype.rb:82]: But are there 2 checks or just the 1?  Ultimately, I think we should have just one check.

Comment (satmandu) [reply packages/freetype.rb:82]: There is an existing check at the moment, and this adds a second check in the post install.

As this second check isn't universal, the first (existing) check is still useful to tell us how the second check should be written. (I.e., we need to know which conflicting files, from which package, should be considered to be superseding.)
