### PR TITLE
Adjust dbus deps & don't require for non-X11 installs

### LINKED ISSUE #5976: If X and other things aren't installed, a new shell raises errors.
```
$ source ~/.bashrc
dbus-launch: error while loading shared libraries: libSM.so.6: cannot open shared object file: No such file or directory
dbus-update-activation-environment: error: unable to connect to D-Bus: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
```

```
$ crew list installed
acl
attr
autoconf
automake
bash
binutils
bison
brotli
bz2
c_ares
ca_certificates
cmake
compressdoc
crew_profile_base
dbus
diffutils
docbook_xml412
docbook_xml42
docbook_xml43
docbook_xml44
docbook_xml45
docbook_xml50
docbook_xml51
docbook_xsl
docbook_xsl_nons
doxygen
e2fsprogs
elfutils
expat
filecmd
flex
fop
gcc11
gcc_tools
gdbm
gettext
git
glibc
gmp
gnutls
groff
gtk_doc
help2man
icu4c
intltool
isl
itstool
jdk8
jq
krb5
less
libarchive
libcyrussasl
libdb
libedit
libffi
libgcrypt
libgpgerror
libidn2
libmetalink
libnghttp2
libpipeline
libpsl
libseccomp
libsigsegv
libssp
libtasn1
libtirpc
libtool
libunbound
libunistring
libxml2
libxslt
libyaml
linuxheaders
llvm
lz4
lzip
m4
make
mandb
manpages
mawk
meson
most
mpc
mpfr
ncurses
nettle
ninja
openldap
openssl
p11kit
patch
pcre
pcre2
perl
perl_locale_messages
perl_text_unidecode
perl_unicode_eastasianwidth
perl_xml_parser
pixz
pkgconfig
py3_libxml2
py3_nuitka
py3_pip
py3_setuptools
py3_wheel
python2
python3
rdfind
readline
rtmpdump
ruby
samurai
sed
slang
sqlite
symlinks
texinfo
trousers
uchardet
ucl
unzip
upx
util_macros
valgrind
xmlcatmgr
xzutils
zip
zlibpkg
zstd
```

Perhaps the dbus fixes should be added to a chromebrew package and not to crew_profile_base itself.

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #5976 

- Dbus deps are now appropriately enumerated
- Moves the dbus env.d file to the dbus package.
- This keeps dbus from pulling in a bunch of X11 deps on a non-X11 install of chromebrew
- I am not updating dbus binaries since I don't want to create a broken i686 binary (hence the use of postinstall.)
- https://github.com/chromebrew/crew-profile-base can be updated in a separate PR.
- Thanks to @saltedcoffii for noticing this issue and pointing it out.

Works properly:
- [x] x86_64

### CODE REVIEW

File: packages/dbus.rb [hunk 1]
```diff
@@ -36,4 +39,20 @@ def self.build
...
+      [[ "\$DBUS_SESSION_BUS_ADDRESS"=="disabled:" ]] && unset DBUS_SESSION_BUS_ADDRESS
+      if [ -z "\${DBUS_SESSION_BUS_ADDRESS}" ]; then
+        # if not found, launch a new one
+        eval `dbus-launch --sh-syntax`
+        # echo "D-Bus per-session daemon address is: \$DBUS_SESSION_BUS_ADDRESS"
+      fi
+      dbus-update-activation-environment --all
+    DBUSCONFIGEOF
+    IO.write("#{CREW_PREFIX}/etc/env.d/dbus", @dbusconfigenv)
+  end
```
Comment (uberhacker) [inline packages/dbus.rb:57]: This is definitely better to put in install rather than postinstall.  Of course, that would require new binaries.

Comment (satmandu) [reply packages/dbus.rb:57]: Let's do that then.

Comment (satmandu) [reply packages/dbus.rb:41]: Could you rebuild for i686?

Comment (satmandu) [reply packages/dbus.rb:45]: Actually, this needs work. I get a `libaudit.h` not found error on x86_64... Might have to turn off selinux, and maybe we should tweak the runstatedir setting too...

Comment (satmandu) [reply packages/dbus.rb:61]: Compilation fixed. If you can get an i686 build done @uberhacker. I just need to get my armv7l server connected again before I can do that build.

File: packages/crew_profile_base.rb [hunk 2]
```diff
@@ -46,6 +45,10 @@ def self.postinstall
       FileUtils.rm "#{HOME}/.bashrc.bak" if File.exist? "#{HOME}/.bashrc.bak"
       FileUtils.rm "#{HOME}/.zshrc.bak" if File.exist? "#{HOME}/.zshrc.bak"
 
+      # dbus file moved to dbus postinstall, so remove it.
+      FileUtils.rm_f './src/env.d/env.d/03-dbus'
+      FileUtils.rm_f "#{CREW_PREFIX}/etc/env.d/03-dbus"
+
```
Comment (uberhacker) [inline packages/crew_profile_base.rb:51]: Do we need this since the environment has been moved into install instead of postinstall?

File: packages/dbus.rb [hunk 3]
```diff
@@ -3,37 +3,60 @@
...
-     x86_64: 'c777f379f48d88844a5f9eb1f9e38174df8645c6e76845ab0fc8f1ee58034c52',
+  binary_sha256({
+    x86_64: '3a459724ba6e7f14eacc089fb5500b20b7857aa3034cfc58edf2450ad8ac1c02'
   })
 
-  depends_on 'expat'
+  depends_on 'expat' # R
+  depends_on 'libice' # R
+  depends_on 'libsm' # R
+  depends_on 'libx11' # R
```
Comment (uberhacker) [inline packages/dbus.rb:22]: We need libx11 for dbus?  :face_with_head_bandage:

File: packages/crew_profile_base.rb (hunk 2 above)
Comment (satmandu) [reply packages/crew_profile_base.rb:51]: This will clean up the older installed dbus file to avoid running it twice.

File: packages/dbus.rb (hunk 3 above)
Comment (satmandu) [reply packages/dbus.rb:22]: oh yeah. Check out the packages which depend upon it.

File: packages/crew_profile_base.rb (hunk 2 above)
Comment (uberhacker) [reply packages/crew_profile_base.rb:51]: This file wasn't installed by dbus initially? :face_with_head_bandage:

File: packages/dbus.rb [hunk 4]
```diff
@@ -3,37 +3,60 @@
...
+        eval `dbus-launch --sh-syntax`
+        # echo "D-Bus per-session daemon address is: \$DBUS_SESSION_BUS_ADDRESS"
+      fi
+      dbus-update-activation-environment --all
+    DBUSCONFIGEOF
+    IO.write("#{CREW_DEST_PREFIX}/etc/env.d/dbus", @dbusconfigenv)
+  end
+
+  def self.postinstall
+    FileUtils.rm_f "#{CREW_PREFIX}/etc/env.d/03-dbus"
```
Comment (uberhacker) [inline packages/dbus.rb:60]: I don't understand.  We're installing it and then removing it again in postinstall?

File: packages/crew_profile_base.rb (hunk 2 above)
Comment (satmandu) [reply packages/crew_profile_base.rb:51]: This is cleaning up the env.d/03-dbus file from crew_profile_base

File: packages/dbus.rb (hunk 1 above)
Comment (satmandu) [reply packages/dbus.rb:65]: (or not... if none of the packages which depend upon dbus work on i686... maybe it doesn't matter on there?)

File: packages/dbus.rb (hunk 4 above)
Comment (satmandu) [reply packages/dbus.rb:64]: removing the file from crew_profile_base if it exists.

File: packages/crew_profile_base.rb [hunk 5]
```diff
@@ -46,6 +45,10 @@ def self.postinstall
       FileUtils.rm "#{HOME}/.bashrc.bak" if File.exist? "#{HOME}/.bashrc.bak"
       FileUtils.rm "#{HOME}/.zshrc.bak" if File.exist? "#{HOME}/.zshrc.bak"
 
+      # dbus file moved to dbus postinstall, so remove it.
```
Comment (uberhacker) [inline packages/crew_profile_base.rb:48]: Moved to install, not postinstall?
