### PR TITLE
package.rb: Escape some bash special characters being passed to bash via system to fix issues with building.

### LINKED ISSUE #6539: Still unable to build binaries
```
ERROR: sizeof(size_t) doesn't match GLIB_SIZEOF_SIZE_T.
       You probably need to set PKG_CONFIG_LIBDIR
       to point to the right pkg-config files for your
       build target

/usr/local/lib/crew/lib/package.rb:181:in `system': Command failed with exit 1: bash
/usr/local/lib/crew/lib/package.rb:189:in `rescue in system': undefined method `join' for "./configure --prefix=/usr/local --libdir=/usr/local/lib --disable-stack-protector":String (NoMethodError)
        from /usr/local/lib/crew/lib/package.rb:179:in `system'
        from /usr/local/lib/crew/packages/qemu.rb:32:in `build'
        from /usr/local/bin/crew:868:in `block in build_and_preconfigure'
        from /usr/local/bin/crew:854:in `chdir'
        from /usr/local/bin/crew:854:in `build_and_preconfigure'
        from /usr/local/bin/crew:1391:in `build_package'
        from /usr/local/bin/crew:1368:in `resolve_dependencies_and_build'
        from /usr/local/bin/crew:1526:in `block in build_command'
        from /usr/local/bin/crew:1522:in `each'
        from /usr/local/bin/crew:1522:in `build_command'
        from /usr/local/bin/crew:1672:in `<main>'
/usr/local/lib/crew/lib/package.rb:181:in `system': Command failed with exit 1: bash (RuntimeError)
        from /usr/local/lib/crew/lib/package.rb:181:in `system'
        from /usr/local/lib/crew/packages/qemu.rb:32:in `build'
        from /usr/local/bin/crew:868:in `block in build_and_preconfigure'
        from /usr/local/bin/crew:854:in `chdir'
        from /usr/local/bin/crew:854:in `build_and_preconfigure'
        from /usr/local/bin/crew:1391:in `build_package'
        from /usr/local/bin/crew:1368:in `resolve_dependencies_and_build'
        from /usr/local/bin/crew:1526:in `block in build_command'
        from /usr/local/bin/crew:1522:in `each'
        from /usr/local/bin/crew:1522:in `build_command'
        from /usr/local/bin/crew:1672:in `<main>'
```

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #6539

- Another attempt at this. This escapes some bash special characters.
- Please help test this @uberhacker @supechicken @saltedcoffii by running the code to pull this file below and trying to build packages.
- Have only tested this by building `libcap` so far. 
- It would be helpful to create a corpus of sample packages to test with new `crew` updates, such as a package each for `cmake`, `meson`, and `autotools/configure` based building, but that is out of scope for this PR...

Works properly:
- [x] x86_64

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=package_fix_2 CREW_TESTING=1 crew update
```

### CODE REVIEW

File: lib/package.rb [hunk 1]
```diff
@@ -164,13 +164,19 @@ def self.system(*args)
...
+    cmd_args.gsub!('"','\\\\"')
+    cmd_args.gsub!('$','\\\\$')
+    cmd_args.gsub!('`','\\\\`')
 
     begin
       # use bash instead of /bin/sh
       @system_args = ''
       [@system_args, "bash -e -c \"#{cmd_args}\""].reduce(&:concat)
+      # Uncomment following line for debugging.
+      # puts @system_args.orange
```
Comment (uberhacker) [inline lib/package.rb:179]: Rather than uncommenting for debugging, why not add a `-d` switch option?  Should be just a few additional lines of code needed in crew.

File: lib/package.rb [hunk 2]
```diff
@@ -164,13 +164,19 @@ def self.system(*args)
       { exception: true }
     end
 
-    # add -j arg to build commands
+    # Add -j arg to build commands.
     cmd_args.sub(/\b(?<=make)(?=\b)/, " -j#{CREW_NPROC}") unless cmd_args =~ /-j\s*\d+/
+    # Escape special bash characters.
+    cmd_args.gsub!('"','\\\\"')
+    cmd_args.gsub!('$','\\\\$')
+    cmd_args.gsub!('`','\\\\`')
```
Comment (uberhacker) [inline lib/package.rb:172]: Seriously?

File: lib/package.rb (hunk 1 above)
Comment (uberhacker) [reply lib/package.rb:179]: Sorry, `-d` is for disabling color.  Maybe `-D`?

File: lib/package.rb (hunk 2 above)
Comment (satmandu) [reply lib/package.rb:172]: Feel free to make this code better. This is at the "this works to fix the problem" stage. The next step is to optimize it...

File: lib/package.rb (hunk 1 above)
Comment (satmandu) [reply lib/package.rb:179]: I left that just for debugging optimization. If I recall correctly the standard debut flags don't work in `package.rb`...

We can take it out after we are sure this all works well.

**Comment by satmandu** [comment]
Let's get builds working again first? Better is the enemy of good etc etc...

File: lib/package.rb [hunk 3]
```diff
@@ -164,13 +164,19 @@ def self.system(*args)
...
 
     begin
       # use bash instead of /bin/sh
       @system_args = ''
       [@system_args, "bash -e -c \"#{cmd_args}\""].reduce(&:concat)
```
Comment (supechicken) [inline lib/package.rb:177]: Passing the parameters separately to avoid calling `/bin/sh` before calling `bash` (then they don't need to be escaped)?

Comment (supechicken) [reply lib/package.rb:177]: (and use `env` to pass the env variables to bash)
