### PR TITLE
filezilla: add libwebp dep

### LINKED ISSUE #4807: [Filezilla] core package and lib package are incompatible
Running `/usr/local/bin/filezilla` sends :
``` 
Reading locale option from /home/chronos/user/.config/filezilla/filezilla.xml
Fatal Error: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1013,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1014,wx containers,compatible with 2.8).
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #4807 

Add libwebp dep.

Works properly:
- [x] x86_64

### CODE REVIEW

File: packages/filezilla.rb [hunk 1]
```diff
@@ -30,6 +30,7 @@ class Filezilla < Package
   depends_on 'wxwidgets'
   depends_on 'xdg_utils'
   depends_on 'sommelier'
+  depends_on 'libwebp'
```
Comment (uberhacker) [inline packages/filezilla.rb:33]: Can we put this above sommelier so users don't miss the all-important post install message?

Comment (satmandu) [reply packages/filezilla.rb:32]: done
