### PR TITLE
glibc: deal with case of missing libc.so.6

### LINKED ISSUE #7117: [`glibc`]: `#{CREW_LIB_PREFIX}/libc.so.6` missing from prebuilt binary (`armv7l`)(`2.33`)
The `libc.so.6` symlink is missing from the `armv7l` prebuilt tarball (does not exist in `filelist` also)

This lead to errors in `postinstall`:
```
#6 384.5 Performing post-install for glibc...
#6 387.4 /usr/local/lib/crew/packages/glibc.rb:588:in ``': No such file or directory - /usr/local/lib/libc.so.6 (Errno::ENOENT)
#6 387.4 	from /usr/local/lib/crew/packages/glibc.rb:588:in `postinstall'
#6 387.4 	from /usr/local/bin/crew:947:in `block (2 levels) in post_install'
#6 387.4 	from /usr/local/bin/crew:945:in `chdir'
#6 387.4 	from /usr/local/bin/crew:945:in `block in post_install'
#6 387.4 	from /usr/local/lib/ruby/3.1.0/tmpdir.rb:96:in `mktmpdir'
#6 387.4 	from /usr/local/bin/crew:944:in `post_install'
#6 387.4 	from /usr/local/bin/crew:1301:in `block in resolve_dependencies_and_install'
#6 387.4 	from /usr/local/bin/crew:1299:in `each'
#6 387.4 	from /usr/local/bin/crew:1299:in `resolve_dependencies_and_install'
#6 387.4 	from /usr/local/bin/crew:1781:in `block in install_command'
#6 387.4 	from /usr/local/bin/crew:1776:in `each'
#6 387.4 	from /usr/local/bin/crew:1776:in `install_command'
#6 387.4 	from /usr/local/bin/crew:1898:in `<main>'
#6 ERROR: executor failed running [/bin/bash -i -x -o pipefail -c curl -Ls git.io/vddgY | bash]: exit code: 1
------
```

Not sure does it require a rebuild...

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #7117

- Just use alternate libc version detection if binary glibc package does not have libc.so.6 (which is never used anyways.)
- linted package file.

Works properly:
- [x] `x86_64`
- [x] `i686`
- [x] `armv7l`
### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=glibc_fix CREW_TESTING=1 crew update
```

### CODE REVIEW

File: packages/glibc.rb [hunk 1]
```diff
@@ -585,8 +585,12 @@ def self.check
   end
 
   def self.postinstall
-    @crew_libcvertokens = `#{CREW_LIB_PREFIX}/libc.so.6`.lines.first.chomp.split(/\s/)
-    @crew_libc_version = @crew_libcvertokens[@crew_libcvertokens.find_index('version') + 1].sub!(/[[:punct:]]?$/, '')
+    if File.exist?("#{CREW_LIB_PREFIX}/libc.so.6")
+      @crew_libcvertokens = `#{CREW_LIB_PREFIX}/libc.so.6`.lines.first.chomp.split(/\s/)
+      @crew_libc_version = @crew_libcvertokens[@crew_libcvertokens.find_index('version') + 1].sub!(/[[:punct:]]?$/, '')
+    else
+      @crew_libc_version = LIBC_VERSION
```
Comment (supechicken) [inline packages/glibc.rb:592]: Do you mean `@crew_libc_version = version`? (This variable is used to represent the version of `glibc` installed by `crew`)
```ruby
puts "Package glibc version is #{@crew_libc_version}."
```

Comment (satmandu) [reply packages/glibc.rb:593]: I moved the puts line for that so we're not lying about the package version...
