### PR TITLE
binutils: add deps

### LINKED ISSUE #5768: the command "readelf" does not work in binutils because it has missing dependencies.
## Description
Provide a short description of your problem here.
The pre-built binaries provided by crew for `binutils` does not work, the command `readelf` gives an error and complains about missing shared object files.
If you executed a specific command:
```shell
$ readelf
```

Output:
```shell
readelf: error while loading shared libraries: libdebuginfod.so.1: cannot open shared object file: No such file or directory
```

## Versions and system information
chromebrew: `crew --version`
1.9.6
ChromeOS: `cat /etc/lsb-release`
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7259670
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={AAE972E1-A913-C860-B7AB-BF7F267F199B}
CHROMEOS_RELEASE_BOARD=hana-signed-mp-v7keys
CHROMEOS_RELEASE_BRANCH_NUMBER=64
CHROMEOS_RELEASE_BUILDER_PATH=hana-release/R90-13816.64.0
CHROMEOS_RELEASE_BUILD_NUMBER=13816
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=90
CHROMEOS_RELEASE_DESCRIPTION=13816.64.0 (Official Build) stable-channel hana 
CHROMEOS_RELEASE_KEYSET=mp-v7
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=13816.64.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13816.64.0
Model: Lenovo C330

Architecture: `uname -m`
aarch64
What I think needs to be done:
- [ ] Change binutils dependencies to fix this.

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #5768

- Add runtime deps to binutils

Works properly:
- [x] x86_64

### CODE REVIEW

File: packages/binutils.rb [hunk 1]
```diff
@@ -23,7 +23,10 @@ class Binutils < Package
      x86_64: '784c5e9bfd884c411708ae3c2ee1c852022f411794ff109fb7d37e91f124037b'
   })
 
-  depends_on 'flex'
+  depends_on 'zlibpkg' # R
+  depends_on 'glibc' # R
+  depends_on 'elfutils' # R
+  depends_on 'flex' # R
```
Comment (uberhacker) [inline packages/binutils.rb:29]: Since binutils is a core package, we'll need elfutils added to core_packages.txt.

Comment (satmandu) [reply packages/binutils.rb:29]: done
