### PR TITLE
Fix LD_PRELOAD error on installation

### LINKED ISSUE #13463: 🐞 Google has patched Chromebrew it seems
**Describe the bug**
Chromebrew does not install anymore

**To Reproduce**
Try to install Chromebrew using VT2

The issue:
1. Constantly spams that it cant load crew-preload.so
2. Installer crashes when installing crew_profile_base because permission is denied to use tar

### PR DESCRIPTION
**Pull request by ReznorsRevenge1**
Fix LD_PRELOAD error on installation

## Description
Fixes #13463 

## Additional information

Tested & Working properly:
- [x] `x86_64` - See footnote
- [ ] `i686`
- [ ] `armv7l`
##
- [ ] This PR has no manifest .filelist changes. _(Package changes have neither added nor removed files.)_
##
### Run the following to get this pull request's changes locally for testing.
```bash
CREW_REPO=https://github.com/FinnBaltazar1111/chromebrew.git CREW_BRANCH=fix crew update \
&& yes | crew upgrade
```
### Run the following to install this:
```
bash <(curl -L raw.githubusercontent.com/FinnBaltazar1111/chromebrew/refs/heads/fix/install.sh) && . ~/.bashrc
```

For some reason, when you try to install other packages after Chromebrew itself finishes installing, it gets stuck on preflight checks. I don't know if it's just an issue for me or if this is a common issue, nor do I know if this error arises from the changes I've made or if this is another main-branch Chromebrew issue. Also, I've tested this purely on `x86_64` (`octopus` `fleex`, chromeOS `126.0.6478.132`, platform version `15886.44.0`, stable channel, with `rootFS` verification on, if any of that matters at all). Testing on other architectures is greatly appreciated!

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -81,9 +81,9 @@ fi
 
 set -a
 # Default chromebrew repo values.
-: "${OWNER:=chromebrew}"
-: "${REPO:=chromebrew}}"
-: "${BRANCH:=master}"
+: "${OWNER:=FinnBaltazar1111}"
```
Comment (uberhacker) [inline install.sh]: Why the change here?

File: install.sh [hunk 2]
```diff
@@ -440,18 +440,18 @@ function extract_install () {
...
         echo_intra "Running upx on ${1}..."
         grep "/usr/local/\(bin\|lib\|lib${CREW_LIB_SUFFIX}\)" < filelist | xargs -P "$(nproc)" -n1 upx -qq -d 2> /dev/null || true
       fi
       # Switch to our glibc for existing binaries if needed.
-      if [[ -d /usr/local/opt/glibc-libs ]]; then
+      if [[ -d "${CREW_PREFIX}/opt/glibc-libs" ]]; then
         if command -v patchelf &> /dev/null; then
           echo_intra "Running patchelf on ${1}..."
-          grep '/usr/local/bin' < filelist | xargs -P "$(nproc)" -n1 patchelf --set-interpreter "${PATCHELF_INTERPRETER}" 2> /dev/null || true
+          grep '/usr/local/\(bin\|libexec\)' < filelist | xargs -P "$(nproc)" -n1 patchelf --set-interpreter "${PATCHELF_INTERPRETER}" 2> /dev/null || true
```
Comment (uberhacker) [inline install.sh]: Might as well abstract `/usr/local` with `${CREW_PREFIX}` here too.

File: install.sh (hunk 1 above)
Comment (ReznorsRevenge1) [reply install.sh]: idk, I was just trying stuff

Comment (ReznorsRevenge1) [reply install.sh]: This is just the configuration I've found to successfully install, but I can try without that change later.

**Comment by ReznorsRevenge1** [comment]
I'm pretty sure `356a784` fixes the preflight check error. I'll convert this into a regular PR.

File: install.sh [hunk 3]
```diff
@@ -82,7 +82,7 @@ fi
 set -a
 # Default chromebrew repo values.
 : "${OWNER:=chromebrew}"
-: "${REPO:=chromebrew}}"
+: "${REPO:=chromebrew}"
```
Comment (satmandu) [inline install.sh:85]: Nice catch!

**Review by satmandu — DISMISSED** [review]
Unit tests are failing.

File: lib/package.rb
Comment (satmandu) [inline lib/package.rb]: Your changes have uncovered a subtle bug! The `arch_flags_override` needs to be checked with `arch_flags_override?`, otherwise it sets the value to true! And dropping the `nil` into the hash causes this to break!

So we should fix this, otherwise packages like valgrind, which use `arch_flags_override`, will break.

But we also need to revert the change in https://github.com/chromebrew/chromebrew/pull/14582/changes#diff-34d050763e06f484630f7de20b80d861d02267b255c72a0d8f1ac36f4aed7b3bR417

Comment (satmandu) [reply lib/package.rb]: Fixed in https://github.com/chromebrew/chromebrew/pull/14582/changes/721b885a6bc3805e06b7316b6e1ba522c675af00

**Comment by satmandu** [comment]
Thank you for your work, @FinnBaltazar1111, fixing these bugs!

**Review by satmandu — APPROVED** [review]

**Comment by ReznorsRevenge1** [comment]
@satmandu thanks for your help! i've been a bit busy lately so i appreciate your work on this during my absence. looks like all checks pass now, so are we ready to consider merging?

**Review by uberhacker — APPROVED** [review]

**Comment by satmandu** [comment]
It's possible this breaks installs on armv7l, and also maybe i686.

If so, we will have to add back the code that doesn't install gems that may need compiles until later.

**Comment by satmandu** [comment]
Here's the container build failure:

**Comment by uberhacker** [comment]
> Here's the container build failure:
> 
> 

Test improvements needed?
