### PR TITLE
[libtinfo] Remove source link as it is not needed at install

### LINKED ISSUE #4729: [libtinfo] Failed to download source
```shell
libtinfo: Missing ncurses library reference.
https://www.gnu.org/software/ncurses/
version 0.22-1
No precompiled binary available for your platform, downloading source...
########################################################################################### 100%
########################################################################################### 100%
########################################################################################### 100%
########################################################################################### 100%
########################################################################################### 100%
########################################################################################### 100%
########################################################################################### 100%
########################################################################################### 100%
########################################################################################### 100%
########################################################################################### 100%
########################################################################################### 100%
########################################################################################### 100%
########################################################################################### 100%
########################################################################################### 100%
########################################################################################### 100%
########################################################################################### 100%
########################################################################################### 100%
########################################################################################### 100%
########################################################################################### 100%
########################################################################################### 100%
curl: (47) Maximum (50) redirects followed

Traceback (most recent call last):
        12: from /usr/local/bin/crew:1089:in `<main>'
        11: from /usr/local/bin/crew:1003:in `install_command'
        10: from /usr/local/bin/crew:1003:in `each'
         9: from /usr/local/bin/crew:1007:in `block in install_command'
         8: from /usr/local/bin/crew:687:in `resolve_dependencies_and_install'
         7: from /usr/local/bin/crew:775:in `resolve_dependencies'
         6: from /usr/local/bin/crew:775:in `each'
         5: from /usr/local/bin/crew:777:in `block in resolve_dependencies'
         4: from /usr/local/bin/crew:789:in `install'
         3: from /usr/local/bin/crew:499:in `download'
         2: from /usr/local/bin/crew:499:in `chdir'
         1: from /usr/local/bin/crew:506:in `block in download'
/usr/local/bin/crew:506:in `read': No such file or directory @ rb_sysopen - ./libtinfo.so.5 (Errno::ENOENT)
```

### PR DESCRIPTION
**Pull request by supechicken**
Fixes #4729

### CODE REVIEW

File: packages/libtinfo.rb [hunk 1]
```diff
@@ -18,8 +18,8 @@ class Libtinfo < Package
   def self.install
     # See https://forums.opensuse.org/showthread.php/446927-missing-library-libtinfo-so-5.
     # See also http://www.linuxforums.org/forum/installation/6251-libtinfo-so-5-a.html.
-    system "mkdir -p #{CREW_DEST_LIB_PREFIX}"
-    system "ln -sf #{CREW_LIB_PREFIX}/libncurses.so.6 #{CREW_DEST_LIB_PREFIX}/libtinfo.so.5"
-    system "ln -sf #{CREW_LIB_PREFIX}/libncurses.so.6 #{CREW_DEST_LIB_PREFIX}/libtinfo.so.6"
+    FileUtils.mkdir_p "#{CREW_DEST_LIB_PREFIX}"
+    FileUtils.ln_sf "#{CREW_LIB_PREFIX}/libncurses.so.6 #{CREW_DEST_LIB_PREFIX}/libtinfo.so.5"
+    FileUtils.ln_sf "#{CREW_LIB_PREFIX}/libncurses.so.6 #{CREW_DEST_LIB_PREFIX}/libtinfo.so.6"
```
Comment (uberhacker) [inline packages/libtinfo.rb:23]: I believe FileUtils requires a comma to separate the parameters, no?
Also, you could simplify:
```
FileUtils.mkdir_p CREW_DEST_LIB_PREFIX
```
No need to quote an isolated constant.

File: packages/libtinfo.rb [hunk 2]
```diff
@@ -5,8 +5,8 @@ class Libtinfo < Package
   homepage 'https://www.gnu.org/software/ncurses/'
   version '0.22-1'
```
Comment (uberhacker) [inline packages/libtinfo.rb:6]: Bump version?

**Comment by uberhacker** [comment]
Thank you for the update @supechicken!

File: packages/libtinfo.rb (hunk 1 above)
Comment (supechicken) [reply packages/libtinfo.rb]: Done

File: packages/libtinfo.rb (hunk 2 above)
Comment (supechicken) [reply packages/libtinfo.rb]: Done

File: packages/libtinfo.rb [hunk 3]
```diff
@@ -18,8 +18,8 @@ class Libtinfo < Package
   def self.install
     # See https://forums.opensuse.org/showthread.php/446927-missing-library-libtinfo-so-5.
     # See also http://www.linuxforums.org/forum/installation/6251-libtinfo-so-5-a.html.
-    system "mkdir -p #{CREW_DEST_LIB_PREFIX}"
-    system "ln -sf #{CREW_LIB_PREFIX}/libncurses.so.6 #{CREW_DEST_LIB_PREFIX}/libtinfo.so.5"
-    system "ln -sf #{CREW_LIB_PREFIX}/libncurses.so.6 #{CREW_DEST_LIB_PREFIX}/libtinfo.so.6"
+    FileUtils.mkdir_p #{CREW_DEST_LIB_PREFIX}
+    FileUtils.ln_sf '#{CREW_LIB_PREFIX}/libncurses.so.6', '#{CREW_DEST_LIB_PREFIX}/libtinfo.so.5'
+    FileUtils.ln_sf '#{CREW_LIB_PREFIX}/libncurses.so.6', '#{CREW_DEST_LIB_PREFIX}/libtinfo.so.6'
```
Comment (uberhacker) [inline packages/libtinfo.rb:23]: You will need to encapsulate with double instead of single quotes.  Also, no need to wrap the constant in `#{...}`.  `FileUtils.mkdir_p CREW_DEST_LIB_PREFIX` should work.  In the future, please test first before committing changes.

Comment (supechicken) [reply packages/libtinfo.rb]: Done

File: packages/libtinfo.rb [hunk 4]
```diff
@@ -18,8 +18,8 @@ class Libtinfo < Package
   def self.install
     # See https://forums.opensuse.org/showthread.php/446927-missing-library-libtinfo-so-5.
     # See also http://www.linuxforums.org/forum/installation/6251-libtinfo-so-5-a.html.
-    system "mkdir -p #{CREW_DEST_LIB_PREFIX}"
-    system "ln -sf #{CREW_LIB_PREFIX}/libncurses.so.6 #{CREW_DEST_LIB_PREFIX}/libtinfo.so.5"
-    system "ln -sf #{CREW_LIB_PREFIX}/libncurses.so.6 #{CREW_DEST_LIB_PREFIX}/libtinfo.so.6"
+    FileUtils.mkdir_p #{CREW_DEST_LIB_PREFIX}
```
Comment (uberhacker) [inline packages/libtinfo.rb:21]: Does this work?

Comment (supechicken) [reply packages/libtinfo.rb:21]: Yes, just tested.
