### PR TITLE
gcc10 => 10.2.1, with fixed compilation

### LINKED ISSUE #4684: gcc10 compile issue
I've tried to recompile gcc10 (gcc 10.2) with ```system "./contrib/download_prerequisites"``` to make sure I don't have any isl issues. gcc10 seems to compile fine, but I'm getting this weird issue when running gcc (presumably with lot?) and trying to compile evolution_data_server, which seems to indicate a failure to link libzstd properly when compiling gcc.

(Yes libzstd is there in /usr/local/lib64. )

Any ideas on what to change here?

I've tried to recompile libzstd with -pthread since there are reports that might be an issue, but no change.

```
FAILED: src/camel/Camel-1.2.gir 
cd /usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src/camel && /usr/local/bin/cmake -E env "CC='/usr/local/bin/cc'" LDFLAGS= LD_LIBRARY_PATH=\"/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build:/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src:/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src/camel:/usr/local/lib:/usr/local/lib64\" /usr/local/bin/g-ir-scanner --add-include-path=/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build --add-include-path=/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src --add-include-path=/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38 --add-include-path=/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/src --add-include-path=/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src/camel --add-include-path=/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/src/camel --library-path=/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build --library-path=/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src --library-path=/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src/camel --identifier-prefix=Camel --identifier-prefix=camel --add-include-path=/usr/local/share/gir-1.0 --library-path=/usr/local/lib --pkg-export camel-1.2 --c-include=camel/camel.h --cflags-begin -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src/camel -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/src/camel -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38 -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/src -DCAMEL_COMPILATION --cflags-end --verbose --namespace=Camel --nsversion=1.2 --no-libtool --library=camel-1.2 --include=GObject-2.0 --include=Gio-2.0 --include=libxml2-2.0 --warn-all -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src/camel -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/src/camel -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38 -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/src -DCAMEL_COMPILATION --filelist=/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src/camel/Camel_1_2_gir_files --output /usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src/camel/Camel-1.2.gir --accept-unprefixed
/usr/local/bin/cc -E -DCAMEL_COMPILATION -I. -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src/camel -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/src/camel -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38 -I/usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/src -I/usr/local/include/gio-unix-2.0 -I/usr/local/include/libxml2 -I/usr/local/include/libmount -I/usr/local/include/blkid -I/usr/local/lib64/libffi-3.2.1/include -I/usr/local/include/glib-2.0 -I/usr/local/lib64/glib-2.0/include -o g-ir-cpp-idg2u5hu.i -C /usr/local/tmp/crew/evolution-data-server-gnome-3-38.tar.bz2.dir/evolution-data-server-gnome-3-38/build/src/camel/g-ir-cpp-idg2u5hu.c
/usr/local/libexec/gcc/x86_64-cros-linux-gnu/10.2.0/cc1: error while loading shared libraries: libzstd.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/distutils/unixccompiler.py", line 107, in preprocess
    self.spawn(pp_args)
  File "/usr/local/lib/python3.9/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/local/lib/python3.9/distutils/spawn.py", line 87, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/usr/local/bin/cc' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/g-ir-scanner", line 99, in <module>
    sys.exit(scanner_main(sys.argv))
  File "/usr/local/lib64/gobject-introspection/giscanner/scannermain.py", line 590, in scanner_main
    ss, filenames = create_source_scanner(options, args)
  File "/usr/local/lib64/gobject-introspection/giscanner/scannermain.py", line 463, in create_source_scanner
    ss.parse_files(filenames)
  File "/usr/local/lib64/gobject-introspection/giscanner/sourcescanner.py", line 262, in parse_files
    self._parse(headers)
  File "/usr/local/lib64/gobject-introspection/giscanner/sourcescanner.py", line 308, in _parse
    cc.preprocess(tmp_name_cpp,
  File "/usr/local/lib64/gobject-introspection/giscanner/ccompiler.py", line 274, in preprocess
    self.compiler.preprocess(source=source,
  File "/usr/local/lib/python3.9/distutils/unixccompiler.py", line 109, in preprocess
    raise CompileError(msg)
distutils.errors.CompileError: command '/usr/local/bin/cc' failed with exit code 1
```

This is the evolution_data_server.rb I am trying to compile, which gives me the error above at [254/938]
```
# Adapted from Arch Linux evolution-data-server PKGBUILD at:
# https://github.com/archlinux/svntogit-packages/raw/packages/evolution-data-server/trunk/PKGBUILD

require 'package'

class Evolution_data_server < Package
  description 'Centralized access to appointments and contacts'
  version '3.38.2'
  compatibility 'all'
  source_url 'https://gitlab.gnome.org/GNOME/evolution-data-server/-/archive/gnome-3-38/evolution-data-server-gnome-3-38.tar.bz2'
  source_sha256 '30f0ffa0b7779615c782b1d8d21d3fb74083cca0b2b1cf42c340be3c011fbdee'

  #depends_on 'gnome_online_accounts'
  depends_on 'nss'
  #depends_on 'krb5'
  #depends_on 'libgweather'
  #depends_on 'libical'
  #depends_on 'db'
  #depends_on 'libgdata'
  #depends_on 'libphonenumber'
  #depends_on 'intltool' => ':build'
  #depends_on 'gperf' => ':build'
  #depends_on 'gobject_introspection' => ':build'
  #depends_on 'vala' => ':build'
  #depends_on 'gtk_doc' => ':build'
  #depends_on 'boost' => ':build'
  #depends_on 'git' => ':build'
  #depends_on 'cmake' => ':build'
  #depends_on 'ninja' => ':build'
  depends_on 'nspr'
  depends_on 'libsoup'
  depends_on 'gcr'
  #depends_on 'libcanberra'
  depends_on 'libical'


  ENV['LDLAGS'] = '-fno-lto'
  def self.build
    Dir.mkdir 'build'
      Dir.chdir 'build' do
  system "cmake #{CREW_CMAKE_OPTIONS} .. -G Ninja \
  -DENABLE_INTROSPECTION=ON \
  -DENABLE_VALA_BINDINGS=OFF \
  -DENABLE_GTK_DOC=OFF \
  -DWITH_PHONENUMBER=OFF \
  -DWITH_NSPR_INCLUDES=#{CREW_PREFIX}/include/nspr \
  -DWITH_NSS_INCLUDES=#{CREW_PREFIX}/include/nss \
  -DENABLE_OAUTH2=OFF \
  -DENABLE_GOA=OFF \
  -DENABLE_WEATHER=OFF \
  -DENABLE_GOOGLE=OFF \
  -DENABLE_EXAMPLES=OFF \
  -DENABLE_CANBERRA=OFF \
  -DCMAKE_VERBOSE_MAKEFILE=ON"
  end
  system "ninja -v -C build"
  end
  def self.install
  system "DESTDIR=#{CREW_DEST_DIR} ninja -C build install"
  end
end
```

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #4684 

Works properly:
- [x] x86_64
- [x] armv7l
- [x] i686

(There have been no more tags on the 10.2 branch, but the 10.x tree is currently marked as 10.2.1.)

Obviously, this is not fully rubified, but this doesn't appear to break anything, which is good.

(I have binaries for these too.)

### CODE REVIEW

File: packages/gcc10.rb [hunk 1]
```diff
@@ -58,7 +66,7 @@ def self.build
     sed -i '77a #ifndef PATH_MAX' libsanitizer/asan/asan_linux.cpp)"
     Dir.chdir("objdir") do
       case ARCH
-      when 'armv7l', 'aarch64'
+      when 'armv7l', 'armv8l', 'aarch64'
```
Comment (uberhacker) [inline packages/gcc10.rb:69]: Is armv8l a real architecture?  I know of no Chrome(book/box) hardware that has this architecture.

File: packages/gcc10.rb [hunk 2]
```diff
@@ -146,41 +157,41 @@ def self.install
...
+      system "ln -rsv #{CREW_DEST_PREFIX}/bin/#{gcc_arch}-gcc-ranlib-#{gcc_version} #{CREW_DEST_PREFIX}/bin/#{gcc_arch}-gcc-ranlib"
+      system "ln -rsv #{CREW_DEST_PREFIX}/bin/#{gcc_arch}-gfortran-#{gcc_version} #{CREW_DEST_PREFIX}/bin/#{gcc_arch}-gfortran"
+
+      system "ln -rsv #{CREW_DEST_PREFIX}/share/man/man1/cpp-#{gcc_version}.1.gz #{CREW_DEST_PREFIX}/share/man/man1/cpp.1.gz"
+      system "ln -rsv #{CREW_DEST_PREFIX}/share/man/man1/g++-#{gcc_version}.1.gz #{CREW_DEST_PREFIX}/share/man/man1/g++.1.gz"
+      system "ln -rsv #{CREW_DEST_PREFIX}/share/man/man1/gcc-#{gcc_version}.1.gz #{CREW_DEST_PREFIX}/share/man/man1/gcc.1.gz"
+      system "ln -rsv #{CREW_DEST_PREFIX}/share/man/man1/gcov-#{gcc_version}.1.gz #{CREW_DEST_PREFIX}/share/man/man1/gcov.1.gz"
+      system "ln -rsv #{CREW_DEST_PREFIX}/share/man/man1/gcov-dump-#{gcc_version}.1.gz #{CREW_DEST_PREFIX}/share/man/man1/gcov-dump.1.gz"
+      system "ln -rsv #{CREW_DEST_PREFIX}/share/man/man1/gcov-tool-#{gcc_version}.1.gz #{CREW_DEST_PREFIX}/share/man/man1/gcov-tool.1.gz"
+      system "ln -rsv #{CREW_DEST_PREFIX}/share/man/man1/gfortran-#{gcc_version}.1.gz #{CREW_DEST_PREFIX}/share/man/man1/gfortran.1.gz"
```
Comment (uberhacker) [inline packages/gcc10.rb:194]: Rubyize symlinks?

File: packages/gcc10.rb (hunk 1 above)
Comment (satmandu) [reply packages/gcc10.rb:69]: That's there solely for the situation where it is building virtualized for building.

The raspberry pi is going to end up being the cheapest arm Chromebox at some point, right?

File: packages/gcc10.rb (hunk 2 above)
Comment (satmandu) [reply packages/gcc10.rb]: Do my changes look right to you?

Comment (uberhacker) [reply packages/gcc10.rb]: Not sure why you need the `-r` option but everything else looks good.

Comment (satmandu) [reply packages/gcc10.rb]: (I meant checking the updated file...)  Argh... I'll figure this out some day.

File: packages/gcc10.rb (hunk 1 above)
Comment (uberhacker) [reply packages/gcc10.rb:68]: Doesn't `lib/const.rb` already have the logic to switch armv8l over to armv7l?

**Comment by satmandu** [comment]
Yes I believe you are right.

**Comment by uberhacker** [comment]
Update install.sh?

**Comment by satmandu** [comment]
I think this is stable, but I'm going to use this to boostrap a ```-flto``` build tonight. Because why not save cpu cycles for everyone with a more optimized build?

**Comment by uberhacker** [comment]
Good call.  Really appreciate all the effort you are putting into this.

**Comment by satmandu** [comment]
If only the llvm with lto compile wasn't such a #^$#^$.

**Comment by satmandu** [comment]
x86_64 compile succesful. Now just waiting for the others.
```
chronos@localhost /usr/local/lib/crew/packages $ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-cros-linux-gnu/10.2.1/lto-wrapper
Target: x86_64-cros-linux-gnu
Configured with: ../configure --prefix=/usr/local --libdir=/usr/local/lib64 --mandir=/usr/local/share/man --build=x86_64-cros-linux-gnu --host=x86_64-cros-linux-gnu --target=x86_64-cros-linux-gnu --enable-checking=release --enable-lto --disable-multilib --enable-threads=posix --disable-werror --disable-libmpx --enable-static --enable-shared --with-pic --program-suffix=-10.2.1 --with-arch-64=x86-64 --with-build-config=bootstrap-lto-lean
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20201229 (GCC) 
```

**Comment by satmandu** [comment]
If this works for you, we can add it to install.sh.

File: packages/gcc10.rb [hunk 3]
```diff
@@ -35,19 +39,27 @@ class Gcc10 < Package
...
   depends_on 'glibc'
   depends_on 'zstd'
-
+  
   def self.preinstall
-    gccver = `gcc -v 2>&1 | tail -1 | cut -d' ' -f3`.chomp
-    abort "GCC version #{gccver} already installed.".lightgreen unless "#{gccver}" == "No" || "#{gccver}" == "not" || "#{gccver}" == "gcc:" || "#{gccver}" == "#{version}"
+    installed_gccver = `gcc -v 2>&1 | tail -1 | cut -d' ' -f3`.chomp
+    gcc_version = version.split("-")[0]
+    abort "GCC version #{installed_gccver} already installed.".lightgreen unless "#{installed_gccver}" == "No" || "#{installed_gccver}" == "not" || "#{installed_gccver}" == "gcc:" || "#{installed_gccver}" == "#{gcc_version}"
```
Comment (uberhacker) [inline packages/gcc10.rb:46]: This section looks too hackish.  There has got to be a more elegant way to do this.

File: packages/gcc10.rb [hunk 4]
```diff
@@ -35,19 +39,27 @@ class Gcc10 < Package
...
   end
 
   def self.build
+    # Set ccache sloppiness as per
+    # https://wiki.archlinux.org/index.php/Ccache#Sloppiness
+    system "ccache --set-config=sloppiness=file_macro,locale,time_macros"
+    # Prefix ccache to path.
+    ENV['PATH'] = "#{CREW_LIB_PREFIX}/ccache/bin:#{CREW_PREFIX}/bin:/usr/bin:/bin"
```
Comment (uberhacker) [inline packages/gcc10.rb:54]: What is wrong with putting ccache in a conventional bin directory?  We wouldn't need all this extra `PATH` manipulation then, correct?

Comment (satmandu) [reply packages/gcc10.rb:54]: #{CREW_LIB_PREFIX}/ccache/bin just contains the special ccache symlinks for g++, gcc, etc which all point to /usr/local/bin/ccache or whatever.

This way when a program calls gcc, with the prepended path it actually calls the ccache wrapper.

(And this is ONLY for building gcc.) You don't need ccache installed otherwise.)

File: packages/gcc10.rb (hunk 3 above)
Comment (satmandu) [reply packages/gcc10.rb:46]: Is your concern with the abort line or the generation of the installed_gccver value?

My only change here is to add logic to look at the version in the package file and chop off the dash-subversion since we aren't using a tagged build. (But this is based off of the 10.2.x stable branch.)

File: packages/gcc10.rb (hunk 4 above)
Comment (uberhacker) [reply packages/gcc10.rb:54]: Makes sense.  Carry on then...

File: packages/gcc10.rb (hunk 3 above)
Comment (uberhacker) [reply packages/gcc10.rb:46]: I was the one who added this logic initially so I deserve all the blame.  I just hate everything about how this works.

Comment (satmandu) [reply packages/gcc10.rb:46]: Ah. As my initial goal was just to get a version of gcc that would compile, I was trying to have a light touch on everything else. 

Honestly, I'd just get rid of the whole block.

I think it is better to handle ruby failing due to gcc being uninstalled by putting a wrapper on ruby, not by keeping people from messing up their gcc installs.

(If someone messes up their gcc install.... well... it's a learning experience... nobody is going to do it manually.)

But then you have probably dealt with enough people mucking it up to want to have a check here, since you wrote that code, yes?

Comment (uberhacker) [reply packages/gcc10.rb:46]: Well, the idea initially was to prevent someone from reinstalling gcc and bricking crew.  Since we can now switch gcc versions somewhat gracefully, it might be good to keep this logic.

**Comment by satmandu** [comment]
@uberhacker Any objections to merging this?

```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-cros-linux-gnu/10.2.1/lto-wrapper
Target: x86_64-cros-linux-gnu
Configured with: ../configure --prefix=/usr/local --libdir=/usr/local/lib64 --mandir=/usr/local/share/man --build=x86_64-cros-linux-gnu --host=x86_64-cros-linux-gnu --target=x86_64-cros-linux-gnu --enable-checking=release --enable-lto --disable-multilib --enable-threads=posix --disable-werror --disable-libmpx --enable-static --enable-shared --with-pic --program-suffix=-10.2.1 --with-arch-64=x86-64 --with-build-config=bootstrap-lto-lean
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210105 (GCC) 
```

File: packages/gcc10.rb [hunk 5]
```diff
@@ -132,55 +134,62 @@ def self.install
...
+      FileUtils.ln_s "#{CREW_PREFIX}/bin/gcc-ranlib-#{gcc_version}", "#{CREW_DEST_PREFIX}/bin/#{gcc_arch}-ranlib"
+
+
+      FileUtils.ln_s "#{CREW_PREFIX}/share/man/man1/cpp-#{gcc_version}.1.gz", "#{CREW_DEST_PREFIX}/share/man/man1/cpp.1.gz"
+      FileUtils.ln_s "#{CREW_PREFIX}/share/man/man1/g++-#{gcc_version}.1.gz", "#{CREW_DEST_PREFIX}/share/man/man1/g++.1.gz"
+      FileUtils.ln_s "#{CREW_PREFIX}/share/man/man1/gcc-#{gcc_version}.1.gz", "#{CREW_DEST_PREFIX}/share/man/man1/gcc.1.gz"
+      FileUtils.ln_s "#{CREW_PREFIX}/share/man/man1/gcov-#{gcc_version}.1.gz", "#{CREW_DEST_PREFIX}/share/man/man1/gcov.1.gz"
+      FileUtils.ln_s "#{CREW_PREFIX}/share/man/man1/gcov-dump-#{gcc_version}.1.gz", "#{CREW_DEST_PREFIX}/share/man/man1/gcov-dump.1.gz"
+      FileUtils.ln_s "#{CREW_PREFIX}/share/man/man1/gcov-tool-#{gcc_version}.1.gz", "#{CREW_DEST_PREFIX}/share/man/man1/gcov-tool.1.gz"
+      FileUtils.ln_s "#{CREW_PREFIX}/share/man/man1/gfortran-#{gcc_version}.1.gz", "#{CREW_DEST_PREFIX}/share/man/man1/gfortran.1.gz"
```
Comment (uberhacker) [inline packages/gcc10.rb:192]: `#{CREW_MAN_PREFIX}/man1/...` and `#{CREW_DEST_MAN_PREFIX}/man1/...`?

**Comment by uberhacker** [comment]
No objections if it works fine.  Are you confident enough to update install.sh?

File: packages/gcc10.rb (hunk 5 above)
Comment (satmandu) [reply packages/gcc10.rb]: Done.

**Comment by satmandu** [comment]
@uberhacker Let's merge this and I'll create a separate PR for the install.sh
