### PR TITLE
fix perl stow module

### LINKED ISSUE #5723: Stow is broken
## Description

When I execute `stow` it gives the following error:

```shell
Can't locate Stow.pm in @INC (you may need to install the Stow module) (@INC contains: /usr/local/lib/perl5/site_perl/5.32.1/x86_64-linux-thread-multi /usr/local/lib/perl5/site_perl/5.32.1 /usr/local/lib/perl5/5.32.1/x86_64-linux-thread-multi /usr/local/lib/perl5/5.32.1 /usr/local/lib/perl5/site_perl) at /usr/local/bin/stow line 418.
BEGIN failed--compilation aborted at /usr/local/bin/stow line 418.
```

## Versions and system information
chromebrew: 1.8.15

ChromeOS: 

CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7259670
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={01906EA2-3EB2-41F1-8F62-F0B7120EFD2E}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={01906EA2-3EB2-41F1-8F62-F0B7120EFD2E}
CHROMEOS_RELEASE_BOARD=eve-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=64
CHROMEOS_RELEASE_BUILDER_PATH=eve-release/R90-13816.64.0
CHROMEOS_RELEASE_BUILD_NUMBER=13816
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=90
CHROMEOS_RELEASE_DESCRIPTION=13816.64.0 (Official Build) stable-channel eve 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13816.64.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13816.64.0

Model: Pixelbook

Architecture: x86_64

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #5723 
- Fixes stow
- (Can't generated binaries at the moment, but this should get stow working.)

Works properly:
- [x] x86_64

### CODE REVIEW

File: packages/stow.rb [hunk 1]
```diff
@@ -3,27 +3,20 @@
...
-     x86_64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/stow/2.2.2_x86_64/stow-2.2.2-chromeos-x86_64.tar.xz',
-  })
-  binary_sha256 ({
-    aarch64: '3ea38b90ba0477578caa6a01326587f3826d5829a01f1725a781588fead751bc',
-     armv7l: '3ea38b90ba0477578caa6a01326587f3826d5829a01f1725a781588fead751bc',
-       i686: 'e53ad50ae437b0dd709ba44c91a02aa5b8b9ec8ce2255565690ffce58ec59753',
-     x86_64: '0c51e9d9c4963fd53d93ba87facd08812ad204414df888f14564a420f9f2f664',
-  })
+  source_url 'https://ftpmirror.gnu.org/stow/stow-2.3.1.tar.gz'
+  source_sha256 '09d5d99671b78537fd9b2c0b39a5e9761a7a0e979f6fdb7eabfa58ee45f03d4b'
```
Comment (uberhacker) [inline packages/stow.rb:10]: No binaries?

Comment (satmandu) [reply packages/stow.rb:10]: Maintainance on power at my apartment means my build servers are off. but this builds really quickly, so for the person who needed this working, this should fix it.

**Comment by satmandu** [comment]
This is now part of the perl rebuild PR...
