### PR TITLE
Edit Mesa package

### LINKED ISSUE #3053: [mesa] Unable to build
```
./rasterizer/jitter/gen_builder.hpp:76:97: error: invalid conversion from ‘llvm::Value*’ to ‘unsigned int’ [-fpermissive]
     return IRB()->CreateMemMove(Dst, Src, Size, Align, isVolatile, TBAATag, ScopeTag, NoAliasTag);
                                                                                                 ^
In file included from ./rasterizer/jitter/jit_pch.hpp:46:0,
                 from ./rasterizer/jitter/JitManager.h:32,
                 from swr_shader.cpp:27:
/usr/local/include/llvm/IR/IRBuilder.h:494:13: note:   initializing argument 2 of ‘llvm::CallInst* llvm::IRBuilderBase::CreateMemMove(llvm::Value*, unsigned int, llvm::Value*, unsigned int, uint64_t, bool, llvm::MDNode*, llvm::MDNode*, llvm::MDNode*)’
   CallInst *CreateMemMove(Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign,
             ^~~~~~~~~~~~~
In file included from ./rasterizer/jitter/builder.h:157:0,
                 from swr_shader.cpp:35:
./rasterizer/jitter/gen_builder.hpp: In member function ‘llvm::Value* SwrJit::Builder::INVARIANT_GROUP_BARRIER(llvm::Value*)’:
./rasterizer/jitter/gen_builder.hpp:981:19: error: ‘class llvm::IRBuilder<>’ has no member named ‘CreateInvariantGroupBarrier’; did you mean ‘CreateInvariantStart’?
     return IRB()->CreateInvariantGroupBarrier(Ptr);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                   CreateInvariantStart
  CXX      libmesaswr_la-swr_loader.lo
  CXX      rasterizer/common/libmesaswr_la-formats.lo
make[5]: *** [Makefile:2883: libmesaswr_la-swr_shader.lo] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: Leaving directory '/usr/local/tmp/crew/mesa-18.3.1.tar.xz.dir/mesa-18.3.1/src/gallium/drivers/swr'
make[4]: *** [Makefile:1891: all] Error 2
make[4]: Leaving directory '/usr/local/tmp/crew/mesa-18.3.1.tar.xz.dir/mesa-18.3.1/src/gallium/drivers/swr'
make[3]: *** [Makefile:634: all-recursive] Error 1
make[3]: Leaving directory '/usr/local/tmp/crew/mesa-18.3.1.tar.xz.dir/mesa-18.3.1/src/gallium'
make[2]: *** [Makefile:895: all-recursive] Error 1
make[2]: Leaving directory '/usr/local/tmp/crew/mesa-18.3.1.tar.xz.dir/mesa-18.3.1/src'
make[1]: *** [Makefile:680: all] Error 2
make[1]: Leaving directory '/usr/local/tmp/crew/mesa-18.3.1.tar.xz.dir/mesa-18.3.1/src'
make: *** [Makefile:692: all-recursive] Error 1
mesa failed to install: `make V=0 -j2` exited with 2
```

### PR DESCRIPTION
**Pull request by JL2210**
Does not bump version, as Mesa is uninstallable at this point in time.
Fixes #3053

### CODE REVIEW

**Comment by JL2210** [comment]
I'm checking this right now, I might have to forcefully disable LLVM instead of just not enabling it.

**Comment by JL2210** [comment]
All right. This ought to be good.

**Comment by JL2210** [comment]
This is frustrating. I'm looking for a fix right now.

**Comment by JL2210** [comment]
Here we go. This should work now. @uberhacker?

File: packages/mesa.rb [hunk 1]
```diff
@@ -28,7 +28,11 @@ class Mesa < Package
   depends_on 'libxshmfence'
   depends_on 'elfutils'
   depends_on 'llvm'
```
Comment (uberhacker) [inline packages/mesa.rb]: I think you can reduce the dependencies here.  A LOT of these are already installed from other packages.

Comment (JL2210) [reply packages/mesa.rb]: Yeah. Which ones?

Comment (uberhacker) [reply packages/mesa.rb]: Follow the breadcrumb trail.  I think you can whittle it down to:
```
  depends_on 'wayland'
  depends_on 'elfutils'
  depends_on 'llvm'
```
But please confirm.

Comment (JL2210) [reply packages/mesa.rb]: Nope. All it installs is `python27`.

Comment (JL2210) [reply packages/mesa.rb]: I have a (slow) script that does it with `cut` and `tac`, but it requires the package file. Let me try that.

Comment (JL2210) [reply packages/mesa.rb]: If you add `libdrm` to that, then it's fine.

Comment (uberhacker) [reply packages/mesa.rb]: That makes sense since that was added recently.
