### PR TITLE
install.sh: don't fail on chown of missing folders in /usr/local

### LINKED ISSUE #5119: [install.sh] producing error
## Description
When I try to run the install script on a freshly recovered and power-washed machine in developer mode, I get an error.

```shell
curl -Ls git.io/vddgY | bash
```

Output:
```shell
chown: cannot access '/usr/local/bin': No such file or directory.
```

## Versions and system information
**ChromeOS:**
```shell
CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=7069196
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={55DA7A1B-DCE6-47E6-95EC-0CCB7AC432F5}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={55DA7A1B-DCE6-47E6-95EC-0CCB7AC432F5}
CHROMEOS_RELEASE_BOARD=soraka-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=111
CHROMEOS_RELEASE_BUILDER_PATH=soraka-release/R87-13505.111.0
CHROMEOS_RELEASE_BUILD_NUMBER=13505
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=87
CHROMEOS_RELEASE_DESCRIPTION=13505.111.0 (Official Build) stable-channel soraka
CHROMEOS_RELEASE_KEYSET=mp
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=13505.111.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13505.111.0
```

**Model:** HP Chromebook x2

**Architecture:**
x86_64

## Additional information
A few weeks ago the script was working fine on my machine. Can't say for sure if a change to the install script or an update to ChromeOS is what is now this issue.

EDIT: Using last version of install.sh worked fine for me.

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #5119 

Works properly:
- [x] x86_64

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -40,7 +40,7 @@ esac
 
 # This will allow things to work without sudo
 crew_folders="bin cache doc docbook etc include lib lib$LIB_SUFFIX libexec man sbin share tmp var"
-for folder in $crew_folders ; do sudo chown -R "$(id -u)":"$(id -g)" "${CREW_PREFIX}"/"$folder" ; done
+for folder in $crew_folders ; do sudo chown -R "$(id -u)":"$(id -g)" "${CREW_PREFIX}"/"$folder" || true ; done
```
Comment (supechicken) [inline install.sh:43]: This may ignore any error other than `no such directory` in `chown`,  why not check the dir exist before `chown`?
```shell
cd ${CREW_PREFIX}
if [ -d ${folder} ] || [ -L ${folder} ]; then sudo chown -R $(id -u):$(id -g) ${folder}; fi
```

Comment (satmandu) [reply install.sh]: This is a much better approach. Thanks!

Comment (satmandu) [reply install.sh]: How do you feel about the new way? Testing it now...

Comment (supechicken) [reply install.sh]: Looks good to me :) We can also simplify the `[ -d ${folder} ] || [ -L ${folder} ]` part to `[ -d ${folder} -o -L ${folder} ]`

File: install.sh [hunk 2]
```diff
@@ -40,7 +40,12 @@ esac
 
 # This will allow things to work without sudo
 crew_folders="bin cache doc docbook etc include lib lib$LIB_SUFFIX libexec man sbin share tmp var"
-for folder in $crew_folders ; do sudo chown -R "$(id -u)":"$(id -g)" "${CREW_PREFIX}"/"$folder" ; done
+for folder in $crew_folders
+do
+  if [ -d "${CREW_PREFIX}"/"${folder}" ] || [ -L "${CREW_PREFIX}"/"${folder}" ]; then
```
Comment (uberhacker) [inline install.sh:45]: I don't think we should be changing permissions on symlinks.

File: install.sh [hunk 3]
```diff
@@ -40,7 +40,12 @@ esac
...
 # This will allow things to work without sudo
 crew_folders="bin cache doc docbook etc include lib lib$LIB_SUFFIX libexec man sbin share tmp var"
-for folder in $crew_folders ; do sudo chown -R "$(id -u)":"$(id -g)" "${CREW_PREFIX}"/"$folder" ; done
+for folder in $crew_folders
+do
+  if [ -d "${CREW_PREFIX}"/"${folder}" ] || [ -L "${CREW_PREFIX}"/"${folder}" ]; then 
+    sudo chown -R "$(id -u)":"$(id -g)" "${CREW_PREFIX}"/"${folder}"
+  fi
+done
 sudo chown "$(id -u)":"$(id -g)" "${CREW_PREFIX}"
```
Comment (uberhacker) [inline install.sh:49]: Is this line redundant?

**Comment by uberhacker** [comment]
This has a conflict with #5121 which was recently merged.  Please resolve conflicts locally and commit.

File: install.sh (hunk 3 above)
Comment (satmandu) [reply install.sh:49]: No. We need to chown just /usr/local too (non-recursively) too.

File: install.sh (hunk 2 above)
Comment (satmandu) [reply install.sh]: adjusted

**Comment by uberhacker** [comment]
I really wish this wasn't merged.  Please DO NOT merge your own commits @satmandu.  This is your second warning.

**Comment by satmandu** [comment]
This is my fault from a lack of reading comprehension. I read that comment above where you said "resolve conflicts and commit" as "resolve commits and commit [PR]".
