### PR TITLE
working minecraft

### LINKED ISSUE #5879: Checksum mismatch on 'minecraft' package
## Description
I tried to install the 'minecraft' package. But it throws an error: 'Checksum mismatch. 😔 Try again.'
I already did crew update, crew upgrade, nothing works.

I did:
```shell
crew install minecraft
```

Output:
```minecraft: A sandbox video game developed by Mojang Studios AB.
https://minecraft.net
Version: 2.2.1867
License: Mojang
Performing pre-flight checks...
No precompiled binary available for your platform, downloading source...
############################################################################################################################################## 100.0%
Checksum mismatch. 😔 Try again.
```

## Versions and system information
chromebrew: `1.11.1`

ChromeOS:
```CHROMEOS_RELEASE_APPID={87EFFACE-864D-49A5-9BB3-4B050A7C227A}
CHROMEOS_BOARD_APPID={87EFFACE-864D-49A5-9BB3-4B050A7C227A}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
DEVICETYPE=OTHER
CHROMEOS_RELEASE_BOARD=chromeover64
CHROMEOS_DEVSERVER=https://cloudready-free-update-server-2.neverware.com/
GOOGLE_RELEASE=89.4.44
CHROMEOS_RELEASE_BUILD_NUMBER=13729
CHROMEOS_RELEASE_BRANCH_NUMBER=85
CHROMEOS_RELEASE_CHROME_MILESTONE=89
CHROMEOS_RELEASE_PATCH_NUMBER=2021_06_04_2041
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_KEYSET=devkeys
CHROMEOS_RELEASE_NAME=Chromium OS
CHROMEOS_RELEASE_BUILD_TYPE=Developer Build - neverware
CHROMEOS_RELEASE_VERSION=89.4.44
CHROMEOS_AUSERVER=https://cloudready-free-update-server-2.neverware.com/update
CHROMEOS_RELEASE_DESCRIPTION=89.4.44 (Developer Build - neverware) stable-channel chromeover64
```

Model: Not a Chromebook, just a CloudReady laptop

Architecture: `x86_64`

What I think needs to be done:
- Allow users to skip checksum verifying, or fix it in the 'minecraft' package.
---

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #5879

- Fixes new release of Minecraft launcher.

image

Works properly:
- [x] x86_64

### CODE REVIEW

File: packages/minecraft.rb [hunk 1]
```diff
@@ -3,50 +3,31 @@
...
-          fi
-        else
-          ln -s /usr/local/.config/minecraft $HOME/.var/app/com.mojang.Minecraft/.minecraft
-        fi
-        /usr/local/opt/minecraft-launcher/minecraft-launcher
+        # Minecraft launcher documentation is at:
+        # https://minecraft.fandom.com/wiki/Minecraft_Launcher
+        sudo mount -o remount,symfollow /home/chronos/user
+        #{CREW_PREFIX}/bin/minecraft-launcher.elf --workDir #{CREW_PREFIX}/.config/minecraft --tmpDir #{CREW_PREFIX}/tmp $@
+        sudo mount -o remount,nosymfollow /home/chronos/user
```
Comment (uberhacker) [inline packages/minecraft.rb:30]: This is a bit extreme.  Isn't there a more elegant way?

File: packages/minecraft.rb [hunk 2]
```diff
@@ -3,50 +3,31 @@
...
-            rm -r $HOME/.var/app/com.mojang.Minecraft/.minecrft
-            ln -sv /usr/local/.config/minecraft $HOME/.var/app/com.mojang.Minecraft/.minecraft
-          fi
-        else
-          ln -s /usr/local/.config/minecraft $HOME/.var/app/com.mojang.Minecraft/.minecraft
-        fi
-        /usr/local/opt/minecraft-launcher/minecraft-launcher
+        # Minecraft launcher documentation is at:
+        # https://minecraft.fandom.com/wiki/Minecraft_Launcher
+        sudo mount -o remount,symfollow /home/chronos/user
```
Comment (supechicken) [inline packages/minecraft.rb:28]: Can we change the `HOME` variable temporarily to avoid the need of root access?

Comment (satmandu) [reply packages/minecraft.rb:28]: Huh. That's an idea!

File: packages/minecraft.rb (hunk 1 above)
Comment (uberhacker) [reply packages/minecraft.rb:30]: FWIW, the `xdg_base` package symlinks `~/.config` to `/usr/local/.config` but that doesn't help with nosymfollow set.

File: packages/minecraft.rb (hunk 2 above)
Comment (satmandu) [reply packages/minecraft.rb:28]: That works beautifully.

File: packages/minecraft.rb (hunk 1 above)
Comment (satmandu) [reply packages/minecraft.rb]: cross-device symlinks don't work at all any more, so we should modify  `xdg_base` to stop doing that.

**Comment by satmandu** [comment]
@uberhacker Note the hash change.

@supechicken I'm using your hash checking idea!

File: packages/minecraft.rb [hunk 3]
```diff
@@ -3,50 +3,31 @@
...
   homepage 'https://minecraft.net'
-  version '2.2.1867'
+  version '2.2.3200'
   license 'Mojang'
   compatibility 'x86_64'
   source_url 'https://launcher.mojang.com/download/Minecraft.deb'
-  source_sha256 '9a8b6b75db199461ae241fbee6adf65fc6636204c58eb79feff968e307464727'
+  # The minecraft-launcher deb changes often, and we are downloading via https
+  # so maybe it is ok to trust the source package without further hashing.
+  source_sha256 `curl -Ls #{source_url} | sha256sum | tail -n1 | cut -d' ' -f1`.chomp
```
Comment (uberhacker) [inline packages/minecraft.rb:12]: This is problematic since it executes with any command.  Not sure this is the best approach.  Would `source_url 'SKIP'` work better?

Comment (satmandu) [reply packages/minecraft.rb:12]: Ah! i see your point...

File: packages/minecraft.rb [hunk 4]
```diff
@@ -3,50 +3,31 @@
...
 
   depends_on 'libx11'
   depends_on 'jdk8'
-  depends_on 'gtk2'
   depends_on 'gtk3'
+  depends_on 'libcom_err'
   depends_on 'sommelier'
```
Comment (uberhacker) [inline packages/minecraft.rb:18]: Missing `depends_on 'xdg_base'`?

File: packages/minecraft.rb (hunk 3 above)
Comment (uberhacker) [reply packages/minecraft.rb:12]: Another way to fix this is to generate the pre-built binary.

Comment (satmandu) [reply packages/minecraft.rb:12]: I doubt proprietary software like minecraft allows for a license to redistribute....

Comment (satmandu) [reply packages/minecraft.rb:12]: I think we can handle this with `'SKIP'` but we just need to modify crew to have 
```
Digest::SHA256.hexdigest( File.read(cachefile) ) == sha256sum || sha256sum =~ /^SKIP$/i
```
and
```
Digest::SHA256.hexdigest( File.read(filename) ) == sha256sum || sha256sum =~ /^SKIP$/i
```
put in....

File: packages/minecraft.rb (hunk 4 above)
Comment (satmandu) [reply packages/minecraft.rb:18]: It doesn't actually depend upon xdg_base - it creates the necessary folders on its own.
