### PR TITLE
Handbrake binaries

### LINKED ISSUE #4871: [handbrake] Failed to build
```
make[3]: Leaving directory '/usr/local/tmp/crew/HandBrake-1.3.3-source.tar.bz2.dir/HandBrake-1.3.3/build/contrib/x265/x265_3.2.1/8bit'
[ 98%] Built target common
make[3]: Entering directory '/usr/local/tmp/crew/HandBrake-1.3.3-source.tar.bz2.dir/HandBrake-1.3.3/build/contrib/x265/x265_3.2.1/8bit'
Scanning dependencies of target x265-static
make[3]: Leaving directory '/usr/local/tmp/crew/HandBrake-1.3.3-source.tar.bz2.dir/HandBrake-1.3.3/build/contrib/x265/x265_3.2.1/8bit'
make[3]: Entering directory '/usr/local/tmp/crew/HandBrake-1.3.3-source.tar.bz2.dir/HandBrake-1.3.3/build/contrib/x265/x265_3.2.1/8bit'
[100%] Linking CXX static library libx265.a
make[3]: Leaving directory '/usr/local/tmp/crew/HandBrake-1.3.3-source.tar.bz2.dir/HandBrake-1.3.3/build/contrib/x265/x265_3.2.1/8bit'
[100%] Built target x265-static
make[2]: Leaving directory '/usr/local/tmp/crew/HandBrake-1.3.3-source.tar.bz2.dir/HandBrake-1.3.3/build/contrib/x265/x265_3.2.1/8bit'
make[1]: Leaving directory '/usr/local/tmp/crew/HandBrake-1.3.3-source.tar.bz2.dir/HandBrake-1.3.3/build/contrib/x265/x265_3.2.1/8bit'
touch contrib/x265/.stamp.x265_8.build
handbrake failed to build: `make V=0 -j2` exited with 2
```

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #4871

Works properly:
- [x] x86_64

### CODE REVIEW

File: packages/handbrake.rb [hunk 1]
```diff
@@ -9,6 +9,14 @@ class Handbrake < Package
   when 'x86_64'
     source_url 'https://github.com/HandBrake/HandBrake/releases/download/1.3.3/HandBrake-1.3.3-source.tar.bz2'
     source_sha256 '218a37d95f48b5e7cf285363d3ab16c314d97627a7a710cab3758902ae877f85'
+
+    binary_url ({
+      x86_64: 'https://dl.bintray.com/chromebrew/chromebrew/handbrake-1.3.3-1-chromeos-x86_64.tar.xz',
+  })
+    binary_sha256 ({
+      x86_64: '13e06c6458fe918ab1a46deeadcea9415c00be877a333b9bfbe5969c1ca1ba2a',
+  })
```
Comment (uberhacker) [inline packages/handbrake.rb:18]: Can we fix the alignment of `})`?  It helps clarify and prevent confusion.

File: packages/handbrake.rb [hunk 2]
```diff
@@ -25,7 +34,8 @@ def self.patch
 
   def self.build
     ENV['TMPDIR'] = "#{CREW_PREFIX}/tmp"
-    system "./configure --prefix=#{CREW_PREFIX} --enable-x265 --enable-numa --enable-fdk-aac --harden"
+    system "env CFLAGS='-pipe -flto=auto' CXXFLAGS='-pipe -flto=auto' \
+      ./configure --prefix=#{CREW_PREFIX} --enable-x265 --enable-numa --enable-fdk-aac --harden"
```
Comment (uberhacker) [inline packages/handbrake.rb:38]: I assume `#{CREW_OPTIONS}` fails?

Comment (satmandu) [reply packages/handbrake.rb:38]: I didn't try. This was a quick edit just in case it was your build environment which was broken...

File: packages/handbrake.rb (hunk 1 above)
Comment (satmandu) [reply packages/handbrake.rb:18]: That would be ideal... I haven't modified my scripts to generate the URL section properly when all architectures haven't been built.

Feel free to edit it?  I won't be able to get back to this until tomorrow...
