### PR TITLE
xwayland: Fix X symlink

### LINKED ISSUE #4652: [xinit] Failed to execute
```shell
xinit: unable to run server "X": No such file or directory
Use the -- option, or make sure that /usr/local/bin is in your path and
that "X" is a program or a link to the right type of server
for your display.  Possible server names include:

    Xorg        Common X server for most displays
    Xvfb        Virtual frame buffer
    Xfake       kdrive-based virtual frame buffer
    Xnest       X server nested in a window on another X server
    Xephyr      kdrive-based nested X server
    Xvnc        X server accessed over VNC's RFB protocol
    Xdmx        Distributed Multi-head X server
```

Seems the `xorg_server` package doesn't install probability

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #4652

This might be a packaging issue, but I noticed this:
```
ls -aFl /usr/local/bin/X
lrwxrwxrwx. 1 chronos chronos 47 Nov 24 17:11 /usr/local/bin/X -> /usr/local/tmp/crew/dest/usr/local/bin/Xwayland
```

Works properly:
- [x] x86_64

### CODE REVIEW

File: packages/xwayland.rb [hunk 1]
```diff
@@ -151,6 +151,6 @@ def self.install
     system "DESTDIR=#{CREW_DEST_DIR} ninja -C build install"
     FileUtils.mv "#{CREW_DEST_PREFIX}/bin/Xwayland", "#{CREW_DEST_PREFIX}/bin/Xwayland.elf"
     system "install -Dm755 Xwayland_sh #{CREW_DEST_PREFIX}/bin/Xwayland"
-    FileUtils.ln_sf "#{CREW_DEST_PREFIX}/bin/Xwayland", "#{CREW_DEST_PREFIX}/bin/X"
+    system "ln -sfr #{CREW_DEST_PREFIX}/bin/Xwayland #{CREW_DEST_PREFIX}/bin/X"
```
Comment (uberhacker) [inline packages/xwayland.rb:154]: Actually, it should be:
```
FileUtils.ln_sf "#{CREW_PREFIX}/bin/Xwayland", "#{CREW_DEST_PREFIX}/bin/X"
```
In the future, please test before submitting a PR.  It will save me time. :)

Comment (satmandu) [reply packages/xwayland.rb:154]: Touché.

**Comment by satmandu** [comment]
The X symlink is now _properly_ fixed.

**Comment by uberhacker** [comment]
We will need new binaries, correct?  Please remove those and I'll try to generate later this evening after work.

**Comment by satmandu** [comment]
Yes new binaries will be needed. I'll remove those now.
