### PR TITLE
Fix #5612

### LINKED ISSUE #5612: install.sh broken (again 🙄)
Log:
```
 * [new branch]        master                           -> origin/master
 * [new branch]        pr/205                           -> origin/pr/205
 * [new branch]        revert-1030-add-vpnc-package     -> origin/revert-1030-add-vpnc-package
 * [new branch]        revert-1177-update-screenfetch   -> origin/revert-1177-update-screenfetch
 * [new branch]        revert-758-add-moreutils-package -> origin/revert-758-add-moreutils-package
 * [new branch]        revert-760-add-cron-package      -> origin/revert-760-add-cron-package
 * [new branch]        revert-936-update-emacs-package  -> origin/revert-936-update-emacs-package
 * [new branch]        skiman6010-copyright-date-update -> origin/skiman6010-copyright-date-update
 * [new tag]           0.4.1                            -> 0.4.1
 * [new tag]           v0.1                             -> v0.1
 * [new tag]           v0.1.1                           -> v0.1.1
 * [new tag]           v0.2                             -> v0.2
 * [new tag]           v0.2.1                           -> v0.2.1
 * [new tag]           v0.2.1.1                         -> v0.2.1.1
 * [new tag]           v0.2.1.2                         -> v0.2.1.2
 * [new tag]           v0.3                             -> v0.3
 * [new tag]           v0.3.1                           -> v0.3.1
 * [new tag]           v0.4                             -> v0.4
From https://github.com/skycocker/chromebrew
 * branch              master     -> FETCH_HEAD
HEAD is now at 30a1f871 Transition binary repo from Bintray to SourceForge (#5608)
bash: line 202: crew: command not found
```

@uberhacker this is high priority

### PR DESCRIPTION
**Pull request by saltedcoffii**
Fixes #5612

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -187,7 +187,7 @@ done
 sudo ldconfig &> /dev/null || true
 
 # create symlink to 'crew' in ${CREW_PREFIX}/bin/
-ln -sfv "lib/crew/crew" "${CREW_PREFIX}/bin/"
+ln -sfv "../lib/crew/crew" "${CREW_PREFIX}/bin/"
```
Comment (uberhacker) [inline install.sh:190]: No, this will break the binary.  There must be something wrong with your environment.

Comment (saltedcoffii) [reply install.sh:190]: Okay, let's think about this step by step.
ln -s is creating a symlink at `#{CREW_PREFIX}/bin/`. bin is a directory, so it uses the name of the file specified in argument 1, crew. So it creates a binary at `#{CREW_PREFIX}/bin/crew`
Then ln looks to the first argument to find out where this symlink should point. It says `lib/crew/crew` so ln makes that the symlinks relative path. Changed into an absolute path, this would be `#{CREW_PREFIX}/bin/lib/crew/crew`. There's no file there, and there isn't even a directory called `lib` in `/usr/local/bin`.
When the shell tries to run `crew`, the symlink points the shell to `/usr/local/bin/lib/crew/crew`, which doesn't exist, so the shell reports that it can't find an executable called `crew`.
If the symlink is instead made to point to `../lib/crew/crew` the symlink then directs the shell to `/usr/local/bin/../lib/crew/crew`, where the file is. If you remove the `bin/..`, that becomes `/usr/local/lib/crew/crew`, which is the correct path.

Comment (saltedcoffii) [reply install.sh:190]: If you really don't believe me do a fresh install with `curl -#L git.io/vddgY | bash` and watch it fail. Then delete everything in `/usr/local` and run `curl -#L git.io/vddgY | sed -e 's:"lib/crew/crew" "${CREW_PREFIX}/bin/":"../lib/crew/crew" "${CREW_PREFIX}/bin/":' | bash` and watch it work.

**Comment by uberhacker** [comment]
My apologies.  I thought you were trying to relocate the crew binary again.  This is a legit bug.  I would have looked at this earlier but he meetings earlier today.  Day job. :zzz:

**Comment by saltedcoffii** [comment]
🤦🏻
