### PR TITLE
Gnome games collection

### LINKED ISSUE #5351: crew update broken
```
From https://github.com/skycocker/chromebrew
 * branch              master     -> FETCH_HEAD
HEAD is now at c2b88554 Gnome games collection (#5335)
Package lists, crew, and library updated.
Generating compatible packages...
/usr/local/lib/crew/packages/clutter_gtk.rb:7:in `<class:Clutter_gtk>': undefined method `tr' for nil:NilClass (NoMethodError)
        from /usr/local/lib/crew/packages/clutter_gtk.rb:3:in `<top (required)>'
        from <internal:/usr/local/lib64/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib64/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/bin/crew:137:in `set_package'
        from /usr/local/bin/crew:203:in `block in generate_compatible'
        from /usr/local/lib64/ruby/3.0.0/find.rb:49:in `block (2 levels) in find'
        from /usr/local/lib64/ruby/3.0.0/find.rb:48:in `catch'
        from /usr/local/lib64/ruby/3.0.0/find.rb:48:in `block in find'
        from /usr/local/lib64/ruby/3.0.0/find.rb:43:in `each'
        from /usr/local/lib64/ruby/3.0.0/find.rb:43:in `find'
        from /usr/local/bin/crew:200:in `generate_compatible'
        from /usr/local/bin/crew:418:in `update'
        from /usr/local/bin/crew:1069:in `update_command'
        from /usr/local/bin/crew:1097:in `<main>'
```

### PR DESCRIPTION
**Pull request by supechicken666**
Fix #5351 
Sorry, I should really test them

### CODE REVIEW

File: packages/clutter_gtk.rb [hunk 1]
```diff
@@ -4,7 +4,7 @@ class Clutter_gtk < Package
   description 'The Clutter Gtk package is a library providing facilities to integrate Clutter into GTK+ applications.'
   homepage 'https://wiki.gnome.org/Projects/Clutter'
   compatibility 'all'
-  @_app = name.tr('_', '-')
+  @_app = File.basename(__FILE__, '.rb').tr('_', '-')
```
Comment (uberhacker) [inline packages/clutter_gtk.rb:7]: Does this work?
```
@_app = name.to_s.tr('_', '-')
```

Comment (supechicken666) [reply packages/clutter_gtk.rb:7]: Probably no, as the `name` variable is initialized after `set_package` part (the `name` variable only works on `self.*` part)

**Comment by satmandu** [comment]
This would also work:
```
require 'package'

class Clutter_gtk < Package
  description 'Clutter integration with GTK+'
  homepage 'https://gitlab.gnome.org/GNOME/clutter-gtk'
  @_ver = '1.8.4'
  version @_ver
  compatibility 'all'
  source_url "https://gitlab.gnome.org/GNOME/clutter-gtk/-/archive/#{@_ver}/clutter-gtk-#{@_ver}.tar.bz2"
  source_sha256 '450f15f11b8531b49b4613edc282c45989a5c5d65c9cfad48e49494a996ee1ae'

  binary_url({
    aarch64: 'https://dl.bintray.com/chromebrew/chromebrew/clutter_gtk-1.8.4-chromeos-armv7l.tar.xz',
     armv7l: 'https://dl.bintray.com/chromebrew/chromebrew/clutter_gtk-1.8.4-chromeos-armv7l.tar.xz',
       i686: 'https://dl.bintray.com/chromebrew/chromebrew/clutter_gtk-1.8.4-chromeos-i686.tar.xz',
     x86_64: 'https://dl.bintray.com/chromebrew/chromebrew/clutter_gtk-1.8.4-chromeos-x86_64.tar.xz'
  })
  binary_sha256({
    aarch64: '93bdb69bdf105f84ed51414b669bb940bebf9a845e9eb5a786eff29baaf25d6d',
     armv7l: '93bdb69bdf105f84ed51414b669bb940bebf9a845e9eb5a786eff29baaf25d6d',
       i686: '23a33c299da90c6fe606fd734c700a3a5b2ecabcb82e0ff71d38c14546f97877',
     x86_64: '7d67b90529d8ff5c55bf855b04912e4174b918c1615fa4ee04439483d78acae2'
  })

  depends_on 'clutter'
  depends_on 'gtk3'
  depends_on 'libgee'
  depends_on 'gobject_introspection' => ':build'

  def self.build
    system "meson #{CREW_MESON_LTO_OPTIONS} \
      builddir"
    system 'meson configure builddir'
    system 'ninja -C builddir'
  end

  def self.install
    system "DESTDIR=#{CREW_DEST_DIR} ninja -C builddir install"
  end
end
```
