### PR TITLE
util_linux -> 2.38

### LINKED ISSUE #6975: Error trying to login to root with zsh when user chronos runs zsh as shell
## Description

Due to this issue #6971 #6972 and this pull #6974

When I try to log in as root with zsh as the default shell via the chronos user running zsh, I get an error similar to that problem

In the chronos user running zsh I run:
```shell
sudo su
```
Or this:
```shell
sudo zsh
```

I got this error:
```
$ sudo su
su: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
```
and this:
```
$ sudo zsh
zsh: error while loading shared libraries: libgdbm.so.6: cannot open shared object file: No such file or directory
```

## Reproducing

1. Press ```Ctrl + Alt + T```, and type ```shell```
2. Get #6974 pull request's changes locally with ```CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=zsh CREW_TESTING=1 crew update```
3. Install zsh with ```crew install zsh```
4. Change the root shell to zsh with ```sudo chsh -s $(which zsh)```
5. Run ```zsh```
6. Run ```sudo su``` or ```sudo zsh```

## Versions and system information
***
- Architecture: `x86_64` (`x86_64`)
- Kernel version: `5.10.106-brunch-sebanc`
- Chromebrew version: `1.23.11`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`
- Last update in local repository: `734ed5c: zsh -> 5.8.1`
- OS variant: `Chrome OS`
- OS version: `rammus-release/R100-14526.57.0`
- OS channel: `stable-channel`

CHROMEOS_ARC_ANDROID_SDK_VERSION=28
CHROMEOS_ARC_VERSION=8334839
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={625849FA-56A0-4E67-9163-B89BE0C2A6AE}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={625849FA-56A0-4E67-9163-B89BE0C2A6AE}
CHROMEOS_RELEASE_BOARD=rammus-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=57
CHROMEOS_RELEASE_BUILDER_PATH=rammus-release/R100-14526.57.0
CHROMEOS_RELEASE_BUILD_NUMBER=14526
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=100
CHROMEOS_RELEASE_DESCRIPTION=14526.57.0 (Official Build) stable-channel rammus 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=14526.57.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=14526.57.0
***

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #6975

- built with https://github.com/skycocker/chromebrew/pull/6981

Works properly:
- [x] `x86_64`
- [x] `i686`
- [x] `armv7l`

### Run the following to get this pull request's changes locally for testing.
```
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew.git CREW_TESTING_BRANCH=util_linux_2.38 CREW_TESTING=1 crew update
```

### CODE REVIEW

File: packages/util_linux.rb [hunk 1]
```diff
@@ -43,5 +44,8 @@ def self.build
 
   def self.install
     system 'make', "DESTDIR=#{CREW_DEST_DIR}", 'install'
+    # conflict with coreutila
```
Comment (uberhacker) [inline packages/util_linux.rb:47]: coreutils?

Comment (satmandu) [reply packages/util_linux.rb]: Fixed.
