### PR TITLE
Fix downloader for file:// scheme

### LINKED ISSUE #6877: Error in downloader with file:// scheme
```
Precompiled binary available, downloading...
/usr/local/lib/crew/lib/downloader.rb:43:in `downloader': undefined local variable or method `filename' for main:Object (NameError)

        return FileUtils.cp uri.path, filename
                                      ^^^^^^^^
```

### PR DESCRIPTION
**Pull request by uberhacker**
Fixes #6877.

### CODE REVIEW

File: lib/downloader.rb [hunk 1]
```diff
@@ -40,6 +40,11 @@ def downloader (*args)
     when 'file'
       # use FileUtils to copy if it is a local file (the url protocol is file://)
       if File.exist?(uri.path)
+        if args[1].to_s.empty?
+          filename = File.basename(uri.path)
+        else
+          filename = args[1]
+        end
         return FileUtils.cp uri.path, filename
```
Comment (supechicken) [inline lib/downloader.rb:48]: If `args[1]` is a string, we don't need to check if it is valid (easier for debugging, also since this won't involve env variables, it is unlikely that an empty string will be passed instead of `nil` (why pass it if it is empty :) ) )

As above, we can combine the `if else` part with the `return` part:
```ruby
return FileUtils.cp uri.path, args[1] || File.basename(uri.path)
```

Comment (uberhacker) [reply lib/downloader.rb:48]: I'm all for simplifying...if it works. :)
