### PR TITLE
Rebase qtbase to maintained kde/5.15 tree

### LINKED ISSUE #6053: QT5 base package with broken headers : /usr/local/lib/libQt5Core.so.5: undefined symbol: u_strToUpper_68
/usr/local/lib/libQt5Core.so.5: undefined symbol: u_strToUpper_68
see http://ix.io/3uDy

### PR DESCRIPTION
**Pull request by satmandu**
Fixes #6053 

- qtbase needed a rebuild to work with newer dependencies
- qtbase 5.15.2 is no longer maintained as open source, and no longer compiles, but luckily[ kde has taken on the task](https://community.kde.org/Qt5PatchCollection), and they have a working, [patched fork of kde 5.15 at https://invent.kde.org/qt/qt/qtbase/-/tree/kde/5.15](https://invent.kde.org/qt/qt/qtbase/-/tree/kde/5.15) .

Builds properly:
- [x] x86_64
- [x] armv7l
- [x] i686

Works properly:
- [x] x86_64 (needs testing on actual hardware)
- [x] armv7l (needs testing on actual hardware)
- [x] i686 (needs testing on actual hardware)

**Reviewers please test on hardware before merging!**

### CODE REVIEW

**Comment by saltedcoffii** [comment]
Can we use `CREW_ENV_OPTIONS` and `CREW_OPTIONS`

**Comment by satmandu** [comment]
> Can we use `CREW_ENV_OPTIONS` and `CREW_OPTIONS`

I don't think so. The qt build system is... ornery.

File: packages/qtbase.rb [hunk 1]
```diff
@@ -3,23 +3,22 @@
 class Qtbase < Package
   description 'Qt Base (Core, Gui, Widgets, Network, ...)'
   homepage 'https://code.qt.io/cgit/qt/qtbase'
-  @_ver = '5.15.2'
-  version @_ver + '-1'
+  @_ver = 'kde-5.15'
```
Comment (uberhacker) [inline packages/qtbase.rb:6]: Qt should be independent from kde.  Not sure why that is included in the version.

Comment (satmandu) [reply packages/qtbase.rb:6]: Its not dependent upon kde. This is just using the kde patched qtbase, since qt no longer releases patches publicly for the 5.15 series.

Not sure where that info should be put, but it seems kde should get credit for that...

Comment (uberhacker) [reply packages/qtbase.rb:6]: Fair enough.  Somebody might see that and think they need to install KDE dependencies.  That is the only issue I have with including kde in the version.

**Comment by drocsid** [comment]
> Fixes #6053
> 
> * qtbase needed a rebuild to work with newer dependencies
> * qtbase 5.15.2 is no longer maintained as open source, and no longer compiles, but luckily[ kde has taken on the task](https://community.kde.org/Qt5PatchCollection), and they have a working, [patched fork of kde 5.15 at https://invent.kde.org/qt/qt/qtbase/-/tree/kde/5.15](https://invent.kde.org/qt/qt/qtbase/-/tree/kde/5.15) .
> 
> Builds properly:
> 
> * [x]  x86_64
> * [x]  armv7l
> 
> Works properly:
> 
> * [ ]  x86_64 (needs testing on actual hardware)
> * [ ]  armv7l (needs testing on actual hardware)
> 
> **Reviewers please test on hardware before merging!**

what about aarch64? I think that's my arch. How do I double check? What happens on the build?

**Comment by satmandu** [comment]
> > Fixes #6053
> > 
> > * qtbase needed a rebuild to work with newer dependencies
> > * qtbase 5.15.2 is no longer maintained as open source, and no longer compiles, but luckily[ kde has taken on the task](https://community.kde.org/Qt5PatchCollection), and they have a working, [patched fork of kde 5.15 at https://invent.kde.org/qt/qt/qtbase/-/tree/kde/5.15](https://invent.kde.org/qt/qt/qtbase/-/tree/kde/5.15) .
> > 
> > Builds properly:
> > 
> > * [x]  x86_64
> > * [x]  armv7l
> > 
> > Works properly:
> > 
> > * [ ]  x86_64 (needs testing on actual hardware)
> > * [ ]  armv7l (needs testing on actual hardware)
> > 
> > **Reviewers please test on hardware before merging!**
> 
> what about aarch64? I think that's my arch. How do I double check? What happens on the build?

Aarch64 uses an armv7l userland, so the binaries for aarch64 and armv7l are currently the same.

File: packages/qtbase.rb (hunk 1 above)
Comment (satmandu) [reply packages/qtbase.rb:6]: Any suggestions on how you would like the versioning changed? Or should I leave it as is?

Comment (uberhacker) [reply packages/qtbase.rb:6]: It looks like invent.kde.org repo is using Gitlab so use the tagged branch as the version?

**Comment by drocsid** [comment]
> Aarch64 uses an armv7l userland, so the binaries for aarch64 and armv7l are currently the same.

I can test against armv7l then, if it's not too onerous. Can you provide instructions to test?

**Comment by satmandu** [comment]
@drocsid 
Run the following. (Copy and paste the entire thing into the terminal.)
```
CREW_TESTING=1 \
CREW_TESTING_REPO=https://github.com/satmandu/chromebrew \
CREW_TESTING_BRANCH=qtbase \
crew update ; crew remove qtbase ; yes | crew upgrade qtbase
```

**Comment by drocsid** [comment]
> @drocsid
> Run the following. (Copy and paste the entire thing into the terminal.)
> 
> ```
> CREW_TESTING=1 \
> CREW_TESTING_REPO=https://github.com/satmandu/chromebrew \
> CREW_TESTING_BRANCH=qtbase \
> crew update ; crew remove qtbase ; yes | crew upgrade qtbase
> ```

I'm trying to test this by building knotifications that is required by another software I want to build. It looks like I'm having an issue related to glibc library paths, and therefore I am not sure if I have succeeded beyond the past issue. It looks like the build is looking for the following

```
/usr/local/bin/ld: cannot find /usr/local/lib/libc.so.6
/usr/local/bin/ld: cannot find /usr/local/lib/ld-linux-armhf.so.3
``` 

which seem to be both located under /lib . Similarly there have been some other issues related to libc and one created by me so mentioning them here. I could try to create a symlink maybe just for the build. But thought I would at least mention this first.


#5777 #6003

**Comment by satmandu** [comment]
Try `crew reinstall glibc`

**Comment by drocsid** [comment]
> Try `crew reinstall glibc`

That resolved my issue. Why was it missing from the previous installation?

 I am getting further along in my build process. I think the issue is resolved. Then I think you resolved the issue for arm.

**Comment by satmandu** [comment]
Glibc doesn't get reinstalled unless there is a version update... 

But debugging beyond that is complicated, and there was some churn in building a Glibc 2.32 which worked on M92...

File: packages/qtbase.rb (hunk 1 above)
Comment (satmandu) [reply packages/qtbase.rb]: done.

**Comment by drocsid** [comment]
Well I'm happy with this qtbase release for armv7l. Are you going to ship it?

**Comment by satmandu** [comment]
Just waiting for someone to merge it...

**Comment by uberhacker** [comment]
I'm still building the i686 binary unless you generated it already @satmandu?  We still have `compatibility 'all'`, correct?  I won't give up on i686 if the binary works.

**Comment by satmandu** [comment]
I have not rebuilt this yet. But also, I don't really see the point of
building this for i686, as this is only for gui apps...

**Comment by satmandu** [comment]
Did the i686 binary work for you @uberhacker ?

**Comment by uberhacker** [comment]
When I compile, I noticed `QT_VERSION_STR=\"5.15.3\"` so maybe we should use `version 5.15.3`?

**Comment by satmandu** [comment]
Sure. That's reasonable. We just need to reupload the builds to gitlab...

**Comment by uberhacker** [comment]
On i686 actual hardware, I get:
```
make[2]: Leaving directory '/usr/local/tmp/crew/qtbase.20210818161919.dir/qmake'
/usr/local/tmp/crew/qtbase.20210818161919.dir/bin/qmake -install qinstall -exe /usr/local/tmp/crew/qtbase.20210818161919.dir/qmake/qmake /usr/local/tmp/crew/dest/usr/local/share/Qt-5/bin/qmake
Error copying /usr/local/tmp/crew/qtbase.20210818161919.dir/qmake/qmake to /usr/local/tmp/crew/dest/usr/local/share/Qt-5/bin/qmake: Failure to write block
make[1]: *** [Makefile.qmake-aux:280: install_qmake] Error 3
make[1]: Leaving directory '/usr/local/tmp/crew/qtbase.20210818161919.dir/qmake'
make: *** [Makefile:138: sub-qmake-qmake-aux-pro-install_subtargets] Error 2
qtbase failed to build: `make INSTALL_ROOT=/usr/local/tmp/crew/dest install` exited with 2
```

**Comment by satmandu** [comment]
@uberhacker Out of disk space?

**Comment by satmandu** [comment]
Version updated to 5.15.3 .

**Comment by uberhacker** [comment]
@satmandu: Another overnight i686 build attempt succeeded.  You were probably right about the lack of disk space.

**Comment by uberhacker** [comment]
All hardware tests pass!

**Comment by RJVB** [comment]
I just tried to explore the Qt implementation via Qt's assistant in QtTools. I was surprised to see GtK being pulled in (versions 3 AND 4?!), but in the end I got neither the XCB nor the Wayland QPA platform plugins. Is the packaging in some kind of transitional state maybe? And why not use Qt's Wayland backend directly if that's what ChromeOS provides, rather than X11?
