### PR TITLE
[fontconfig] upgrade to 2.13.0, fix libdir

### LINKED ISSUE #1978: [cairo] Unable to install
```
/bin/sed: can't read /usr/local/lib/libfreetype.la: No such file or directory
libtool:   error: '/usr/local/lib/libfreetype.la' is not a valid libtool archive
make[3]: *** [Makefile:2327: libcairo.la] Error 1
make[3]: Leaving directory '/usr/local/tmp/crew/cairo-1.15.10.tar.xz.dir/cairo-1.15.10/src'
make[2]: *** [Makefile:2164: all] Error 2
make[2]: Leaving directory '/usr/local/tmp/crew/cairo-1.15.10.tar.xz.dir/cairo-1.15.10/src'
make[1]: *** [Makefile:914: all-recursive] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/cairo-1.15.10.tar.xz.dir/cairo-1.15.10'
make: *** [Makefile:763: all] Error 2
cairo failed to install: `make V=0 -j2` exited with 2
```
The correct location on `x86_64` systems is `/usr/local/lib64/libfreetype.la`.

### PR DESCRIPTION
**Pull request by lovedheart**
wrong libdir causes build issue for x86_64 architecture.

Should fix #1978

### CODE REVIEW

File: packages/fontconfig.rb [hunk 1]
```diff
@@ -26,8 +20,11 @@ class Fontconfig < Package
   depends_on 'freetype'
 
   def self.build
-      system './configure CFLAGS=" -fPIC" --localstatedir=/usr/local/cache'
-      system 'make'
+    system "./configure \
+          --prefix=#{CREW_PREFIX} \
+          --libdir=#{CREW_LIB_PREFIX} \
+          --localstatedir=/usr/local/cache"
```
Comment (uberhacker) [inline packages/fontconfig.rb]: --localstatedir=#{CREW_PREFIX}/cache?
